### ISSUE TITLE
Replace deprecated terminology

### ISSUE THREAD

**Issue by timja** [jenkinsci/helm-charts#11]
Slave has been deprecated for 4 years
'slave' -> 'agent'

Master recently became a deprecated term and was replaced with controller
'master' -> 'controller'

This can definitely be delivered incrementally.

**Comment by torstenwalter** [comment]
Already replaced "Jenkins master" with "Jenkins server" in the readme. Would controller be the preferred term? It conflict a bit with Kubernetes terminology

Updating all values will take a while and be a breaking change. I suggest to do it either after or together with #13

**Comment by timja** [comment]
Yes controller is the term,

cc @slide and @markyjackson-taulia @oleg-nenashev who are the ones mostly involved in this I believe and can provide more information, and I believe a blog is in progress.

**Comment by markyjackson-taulia** [comment]
You are correct @timja

**Comment by slide** [comment]
It would be hard not to conflict with another piece of software in terms. We recently had a public poll and controller was the top term and the Governance Meeting approved it on August 12 as the replacement.

**Comment by torstenwalter** [comment]
I did a quick research in the chart to look for things which should be addressed:

- `master` key in values file => should be renamed to `controller`
- `master.componentName: "jenkins-master"` in values file => should be changed to `controller.componentName: "controller"`
- many comments
- `slave` in values.yaml

  ```
  slaveListenerPort: 50000
  slaveHostPort:
  # slaveListenerServiceType is the Kubernetes Service type for the JNLP agent service,
  slaveListenerServiceType: "ClusterIP"
  # Optionally assign an IP to the LoadBalancer slaveListenerService LoadBalancer
  # slaveListenerLoadBalancerIP: 1.2.3.4
  slaveListenerServiceAnnotations: {}
  slaveDefaultsProviderTemplate: ""
  slaveConnectTimeout: 5
  slaveReadTimeout: 15
  slaveKubernetesNamespace:
  slaveJenkinsUrl:
  slaveJenkinsTunnel:
  # slaveListenerServiceType: LoadBalancer
  # slaveListenerServiceAnnotations:
  componentName: "jenkins-slave"
  slaveConnectTimeout: 100
  ```

- template file names:
  ```
  jenkins-agent-svc.yaml
  jenkins-backup-cronjob.yaml
  jenkins-backup-rbac.yaml
  jenkins-master-alerting-rules.yaml
  jenkins-master-backendconfig.yaml
  jenkins-master-deployment.yaml
  jenkins-master-ingress.yaml
  jenkins-master-networkpolicy.yaml
  jenkins-master-route.yaml
  jenkins-master-servicemonitor.yaml
  jenkins-master-svc.yaml
  ```
