### ISSUE TITLE
Permission issue when mounting a efs using persistence volume on eks cluster.

### ISSUE THREAD

**Issue by srikavya-kola** [jenkinsci/helm-charts#111]
I'm trying to deploy Jenkins using this helm chart on EKS cluster with EFS persistence volume and a claim, while doing so I'm getting  below error : 
```
Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions ?
touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
```
HELM Jenkins Values used are here - https://github.com/kind-kitty/Helm_Jenkins/blob/83c37fffa2a4967f5e51a58ceaefb792831fcd04/jenkins-values.yaml

only changes I've made in jenkins-values are 
```
persistence:
  enabled: true
  existingClaim: jenkins-pvc
...
sidecars:
  configAutoReload:detected.
    enabled: false
...
ingress:
  enabled: true
  hostName: jenkins.datalabs.com
```

EFS persistence volume and claim are

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins
spec:
  storageClassName: aws-efs
  mountOptions:
    - hard
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - timeo=600
    - retrans=2
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /
    server: fs-bab9082b.efs.eu-north-1.amazonaws.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs
  resources:
    requests:
      storage: 5Gi
  volumeName: jenkins-pv
```
It looked like 'jenkins' user isn't able to perform write operations when we mount EFS as volume, so I tried changing following in jenkins values
```
runAsUser: 0
```
With the above change it started working. I think few other people also facing similar issues - https://stackoverflow.com/questions/43787360/error-with-jenkins-ecs-and-efs.

**Can some one provide some insights if this is an issue that can solved within the helm chart itself or do you prefer us to create our own docker image for jenkins master by running "sudo chown 1000 /var/jenkins_home?"**
