### ISSUE TITLE
Settings in Manage Jenkins > Security > Authorization, are not saved in persistent volume

### ISSUE THREAD

**Issue by ioannisgk** [jenkinsci/helm-charts#1156]
### Describe the bug

I have deployed Jenkins with the default Jenkins Helm chart v5.4.3, I only added `persistence.enabled` `persistence.storageClass` and `persistence.size`. Jenkins is working fine, I can create Jobs and if the jenkins pod is deleted, after it starts up I can see all my jobs in the UI, so the persistent volume is working.

But if I go to **Manage Jenkins > Security > Authorization**, and I change a setting, for example `Authorization: Anyone can do anything` (just select something from the drop down other than the default value) and the jenkins pod is restarted, then if I go on the same page I see that all my settings are lost. The persistent volume does not keep the settings from that page.

I intend to use an authorization plugin for Jenkins users and if the pod is restarted, I will lose my configuration. Is there a solution to this? Maybe I can add a path to the configuration of the persistent volume in the values.yaml of the Helm chart?

Thank you.

### Version of Helm and Kubernetes

```markdown
- Helm: v3.14.4
- Kubernetes: v1.30.3
```

### Chart version

v5.4.3

### What happened?

```bash
1. Deploy a Jenkins Helm chart and configure these properties: persistence.enabled, persistence.storageClass and persistence.size (make sure that you already have a working storage class in your Kubernetes cluster)
2. When the jenkins pod is healthy, login to Jenkins UI and go to Manage Jenkins > Security > Authorization
3. Change the Authorization setting to "Anyone can do anything"
4. Delete the jenkins-helm-0 pod
5. When the jenkins pod is healthy, login to Jenkins UI and go to Manage Jenkins > Security > Authorization
6. You will see that the Authorization setting is reverted to its default value ("Logged-in users can do anything")
```

### What you expected to happen?

I expected that all my changes in Manage Jenkins > Security > Authorization, would be persistent, even if the jenkins pod is restarted, because I have configured the persistent volume in the Helm chart.

### How to reproduce it

Check the steps described in "What happened" section.

**Comment by ioannisgk** [comment]
According to the Helm chart [documentation](https://artifacthub.io/packages/helm/jenkinsci/jenkins#configure-security-realm-and-authorization-strategy), the `securityRealm` and `authorizationStrategy` need to be configured in the Jenkins Configuration as Code (JCasC) plugin.

I tested the chart with the following:
```
controller:
  JCasC:
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "${chart-admin-username}"
          name: "Jenkins Admin"
          password: "${chart-admin-password}"
        - id: user1
          name: "User 1"
          password: user1
    authorizationStrategy: |-
      projectMatrix:
        entries:
        - user:
            name: admin
            permissions:
            - Overall/Administer
        - user:
            name: user1
            permissions:
            - Job/Build
            - Job/Cancel
            - Job/Read
            - Overall/Read
```

With this configuration, I can see that after the jenkins pod is restarted, the user can login and his access configuration is persistent, according to the **Manage Jenkins > Security > Authorization** section.
