### ISSUE TITLE
init container gives java.nio.file.FileSystemException: /.cache: Read-only file system

### ISSUE THREAD

**Issue by f-w** [jenkinsci/helm-charts#1176]
### Describe the bug

Our OpenShift env doesn't allow run as user 1000. `usePodSecurityContext` has no effect on init container. I have to override following values

```yaml
jenkins:
  controller:
    usePodSecurityContext: false
    podSecurityContextOverride:
      runAsGroup: 1010380000
      runAsUser: 1010380000
    containerSecurityContext:
      runAsGroup: 1010380000
      runAsUser: 1010380000
```

### Version of Helm and Kubernetes

```markdown
- Helm: version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.20.10"}
- Kubernetes: v1.26.13+77e61a2
```

### Chart version

5.5.8

### What happened?

```bash
init container throws exception
`java.nio.file.FileSystemException: /.cache: Read-only file system`
```

### What you expected to happen?

no error

**Comment by jonesbusy** [comment]
Duplicate of https://github.com/jenkinsci/helm-charts/issues/506

I confirm the chart works on Openshift/OKD if you let the cluster manage the security context

This is due to the plugin installation manager tool.

You need to ensure to move the cache to a writable location

```
  initContainerEnv:
    - name: CACHE_DIR
      value: "/tmp/cache"
    - name: PLUGIN_DIR
      value: "/tmp/plugins"
```
