### ISSUE TITLE
Private Github server not reachable 

### ISSUE THREAD

**Issue by rajali** [jenkinsci/helm-charts#1184]
### Describe the bug

When I try to create a pipeline or multibranch pipeline and add a Git url I get a prompt saying:
```
Failed to connect to repository : Command "git ls-remote -h -- https://github.onprem.prod/private-repo.git HEAD" returned status code 128:
stdout:
stderr: fatal: unable to access 'https://github.onprem.prod/private-repo.git/': server certificate verification failed. CAfile: none CRLfile: none
```

### Version of Helm and Kubernetes

```markdown
- Helm: v3.15.1
- Kubernetes: v1.28.10
```

### Chart version

5.1.4

### What happened?

```bash
1. I build a custom Jenkins container image based on "jenkins/jenkins:2.450-jdk21"
2. Adding private on-premises certificate authority certificate to java keystore using

 keytool -import -trustcacerts -file /usr/local/share/ca-certificates/OnPremises_Root_CA.crt -alias onprem-root-ca -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit -noprompt
```
3. I use the above image with the jenkins helm chart version 5.1.4, with the values.yml as shared below with proxy and no_proxy config
4. When I manually try to create a pipeline and present the git url for the on-premises github enterprise server I get an error prompt as

```
Failed to connect to repository : Command "git ls-remote -h -- https://github.onprem.prod/private-repo.git HEAD" returned status code 128:
stdout:
stderr: fatal: unable to access 'https://github.onprem.prod/private-repo.git/': server certificate verification failed. CAfile: none CRLfile: none
```

...
```


### What you expected to happen?

No error should be shown, and the repo should be accessible to the pipeline.

### How to reproduce it

```markdown
controller:
  initContainerEnv:
    - name: http_proxy
      value: "http://192.168.64.1:3128"
    - name: https_proxy
      value: "http://192.168.64.1:3128"
    - name: no_proxy
      value: ""
    - name: JAVA_OPTS
      value: "-Dhttps.proxyHost=proxy_host_name_without_protocol -Dhttps.proxyPort=3128 - Dhttp.noProxyHosts=''"
  containerEnv:
    - name: http_proxy
      value: "http://192.168.64.1:3128"
    - name: https_proxy
      value: "http://192.168.64.1:3128"

  JCasC:
    configScripts:
      jenkins-casc: |-
        jenkins:
          globalNodeProperties:
            - envVars:
                env:
                  - key: "PROXY_HOST"
                    value: ${proxy_host}
                  - key: "PROXY_PORT"
                    value: ${proxy_port}
          proxy:
            name: ${proxy_host}
            noProxyHost: ${no_proxy}
            port: ${port}
            testUrl: "https://google.com"

    securityRealm: |-
      saml:
        idpMetadataConfiguration:
          period: 10
          url: ${idpMetadataUrl}
       # rest of the saml config here
```

### Anything else we need to know?

 I have confirmed that the token and user/pass credentials for on-premises Github server work when I configure the GitHub server globally as the "test connection" gives a positive response -- from "Manage" > "System Configuration" > "Configure System".
