### ISSUE TITLE
Option to add or change parameters in security section

### ISSUE THREAD

**Issue by marcelobartsch** [jenkinsci/helm-charts#123]
**Is your feature request related to a problem? Please describe.**

I need to add additional sections under 'security' in the casc configuration file

**Describe the solution you'd like**
It would be nice to be able to change the parameters in
```
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
```
or add new ones, for example 
```
   queueItemAuthenticator:
       authenticators:
       - global:
           strategy: "triggeringUsersAuthorizationStrategy"
```
or other parameters that third party plugins may need

**Describe alternatives you've considered**
I haven't found an alternative beside modify the helm chart directly or do post deploy configuration for this setting.

**Additional context**
