### ISSUE TITLE
Unable to add annotation to jenkins service account via helm chart

### ISSUE THREAD

**Issue by domino-sbr1** [jenkinsci/helm-charts#1233]
### Describe the bug

Below is a piece of `values.yaml` file with the yaml configuration responsible for creating a k8s service account. And although the account creation itself works fine, adding annotations does not. It looks like the service account template contains a reference to non-existent entries.
```
controller:
  serviceAccount:
    create: true
    name: test-jenkins
    annotations:
      test: "test-annotation"
```

Below is the output generated from the above configuration – the annotation section is missing.
```
---
# Source: jenkins/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-jenkins
  namespace: test-jenkins
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "helm.sh/chart": "jenkins-4.9.2"
    "app.kubernetes.io/managed-by": "Helm"
    "app.kubernetes.io/instance": "test-jenkins"
    "app.kubernetes.io/component": "jenkins-controller"
---
```

### Version of Helm and Kubernetes

- Helm: v3.6.1
- Kubernetes: v1.30

### Chart version

jenkins-4.9.2

### What happened?

1. Added annotation to service account definition under controller section in `values.yaml` file
2. Noticed lack of annotation when executed below command:
`kubectl get sa test-jenkins -n test-jenkins -o yaml`

### What you expected to happen?

I want to be able to add annotations to the Jenkins service account

### How to reproduce it

```
controller:
  serviceAccount:
    create: true
    name: test-jenkins
    annotations:
      test: "test-annotation"
```

### Anything else we need to know?

N/A

**Comment by demirfurk4n** [comment]
You may want to check the line 1315 in the official [values.yml](https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml) and then you'll see that serviceAccount configuration should be done as separated object:

```yml
serviceAccount:
  # -- Configures if a ServiceAccount with this name should be created
  create: true

  # The name of the ServiceAccount is autogenerated by default
  #  -- The name of the ServiceAccount to be used by access-controlled resources
  name:
  # -- Configures annotations for the ServiceAccount
  annotations: {}
  # -- Configures extra labels for the ServiceAccount
  extraLabels: {}
  # -- Controller ServiceAccount image pull secret
  imagePullSecretName:
```

Referance: [service-account.yaml ](https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/service-account.yaml) template.
