### ISSUE TITLE
Allow custom Registry in agent image definition

### ISSUE THREAD

**Issue by mparada-suva** [jenkinsci/helm-charts#1349]
### Is your feature request related to a problem? Please describe

Right now the agent image definition is like this:
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml#L954
```
  image:
    # -- Repository to pull the agent jnlp image from
    repository: "jenkins/inbound-agent"
    # -- Tag of the image to pull
    tag: "3301.v4363ddcca_4e7-3"
```

### Describe the solution you'd like

We would like to have a custom registry like, for example, in the controller image definition:
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml#L35
```
  image:
    # -- Controller image registry
    registry: "docker.io"
    # -- Controller image repository
    repository: "jenkins/jenkins"

    # -- Controller image tag override; i.e., tag: "2.440.1-jdk21"
    tag:
```

### Additional context

It is common to have a proxy for external registries, that is the reason why we would like to be able to define it.
