### ISSUE TITLE
A problem with securityRealm and authorizationStrategy config using JCasC section

### ISSUE THREAD

**Issue by Mo0rBy** [jenkinsci/helm-charts#1391]
### Describe the bug

It looks like the `controller.JCasC.securityRealm` and `controller.JCasC.authorizationStrategy` sections are not working correctly.
This is not a massive blocker, as they can still be defined within the `controller.JCasC.configScripts` section.
I am installing the Jenkins Helm chart onto a locally running KinD cluster.

The documentation (in the default `values.yaml`) says that when defined in the `controller.JCasC.<securityRealm/authorizationStrategy>` and not in the `controller.JCasC.configScripts`, the former will be used, but it looks like it doesn't get used at all. I copy/pasted the default values into my values file to ensure they were definitely being used, and my Jenkins instance says that the selected securityRealm in "None", which is incorrect.

Here is a copy/paste from the default `values.yaml` file to better illustrate what I'm talking about. My own comments to help are labelled "my-comment:" to start.
```yaml
    configScripts: {} # my-comment: securityRealm & authorizationStrategy can be set in here, no problems
    #  welcome-message: |
    #    jenkins:
    #      systemMessage: Welcome to our CI\CD server. This Jenkins is configured and managed 'as code'.

    # Allows adding to the top-level security JCasC section. For legacy purposes, by default, the chart includes apiToken configurations
    # -- Jenkins Config as Code security-section
    security:
      apiToken:
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: true

    # Ignored if securityRealm is defined in controller.JCasC.configScripts
    # -- Jenkins Config as Code Security Realm-section
    securityRealm: |- # my-comment: this section doesn't seem to work
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "${chart-admin-username}"
          name: "Jenkins Admin"
          password: "${chart-admin-password}"

    # Ignored if authorizationStrategy is defined in controller.JCasC.configScripts
    # -- Jenkins Config as Code Authorization Strategy-section
    authorizationStrategy: |- # my-comment: this section doesn't seem to work
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false
```

### Version of Helm and Kubernetes

```markdown
- Helm: v3.18.1
- Kubernetes: v1.33.1
```

### Chart version

5.8.55

### What happened?

```bash
1. Install the Helm chart, installing Kubernetes + configuration-as-code plugins
2. Use the `defaultConfig: true` option to get an initial config
3. Go into the webUI and copy/paste the default config into the Helm chart values `JCasC.configScripts` section and set `defaultConfig: false` to avoid conflict errors.
4. Modify the default config (remove `remotingSecurity` (cleans up starting logs), k8s podTemplate (I don't need this), securityRealm + authorizationStrategy sections (want to set these outside the `JCasC.configScripts` section))
5. Restart Jenkins pod to ensure new config is being loaded
6. Go to Manage Jenkins > Security and see that Security Realm is None (as expeceted, nothing is being set).
7. Copy/paste default values.yaml `JCasC.<securityRealm/authorizationStrategy>` sections into your `values.yaml` file (shouldn't be needed as they are default values, but I did this to be sure the values had something and were 100% being set).
8. Helm upgrade and restart Jenkins pod to ensure everything being set
9. Go to Manage Jenkins > Security and see that Security Realm is still None.
10. Set `authorizationStrategy` and `securityRealm` settings within the `JCasC.configScripts` section (you can remove the `JCasC.<securityRealm/authorizationStrategy>` if you want, the `JCasC.configScripts` section will overwrite these anyway according to the docs).
11. Helm upgrade and restart Jenkins pod to ensure new settings are being used.
12. Go to Manage Jenkins > Security and see that Security Realm is now set to "Jenkins' own user database"
```

### What you expected to happen?

I expected the `JCasC.<securityRealm/authorizationStrategy>` to set things correctly and not be required to set these settings within the `JCasC.configScripts` section.

### How to reproduce it

```markdown

```

**Comment by Mo0rBy** [comment]
@itsvshreyas Not to my knowledge

**Comment by itsvshreyas** [comment]
@Mo0rBy , I would like to work on this. Could you please assign this to me?

**Comment by itsvshreyas** [comment]
@Mo0rBy , When you are using default configuration, are you seeing any error in the pod logs? Especially when it is trying to access the configmap - jenkins-jenkins-jcasc-config

**Comment by itsvshreyas** [comment]
@Mo0rBy , Even I am not from dev team. But let me try it out and reproduce it. If I am able to identify and fix, I will put a PR.

**Comment by h0tw1r3** [comment]
This is working for me with 5.8.56. Haven't tried a newer chart yet.

```
controller:
  JCasC:
    securityRealm: |-2
      saml:
        binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        displayNameAttributeName: "displayname"
        emailAttributeName: "email"
        groupsAttributeName: "group"
        idpMetadataConfiguration:
          period: 0
          url: "..."
          xml: "..."
        logoutUrl: "..."
        maximumAuthenticationLifetime: 86400
        usernameAttributeName: "username"
        usernameCaseConversion: "none"
    authorizationStrategy: |-2
      projectMatrix:
        entries:
          - user:
              name: admin
              permissions:
                - Overall/Administer
          - group:
              name: jenkins-admin
              permissions:
                - Overall/Administer
          - group:
              name: authenticated
              permissions:
                - Overall/Read
                - Job/Read
                - View/Read
```
