### ISSUE TITLE
jenkins-plugin-cli cannot be run behind proxy on startup

### ISSUE THREAD

**Issue by alistaircross** [jenkinsci/helm-charts#159]
When using helm to install/upgrade jenkins there is a message:

`"Error getting update center json"`

that causes the copy-default-config init container to fail. My understanding is that it is caused by:

`jenkins-plugin-cli --war "/usr/share/jenkins/jenkins.war" --plugin-file "/var/jenkins_home/plugins.txt"`

I was able to revert my upgrade, ssh into my container and add "/var/jenkins_home/initialization-completed" as well as the "initializeOnce: true" value in my values file, and then do an upgrade that skips the init step.

That's fine for an upgrade but it's my belief behind a proxy we will not be able to stand up a new version, as the proxy values are ignored by the jenkins-plugin-cli.

I have confirmed this by exec into the container and seeing the following:

`jenkins@jenkins-7dd68ccddd-q8gsz:~/logs$ jenkins-plugin-cli --war "/usr/share/jenkins/jenkins.war" --plugin-file "/var/jenkins_home/plugins.txt"
Error getting update center json`

**Version of Helm and Kubernetes**:

Helm Version: "v3.4.1"
Kubernetes Version: "v1.18.12"

**Which version of the chart**:

jenkins-2.19.0 

Some values that I believe are key:

`  initContainerEnv:
    - name: http_proxy
      value: "http://my,proxy.com:3128/"
    - name: https_proxy
      value: "http://my,proxy.com:3128/"
    - name: no_proxy
      value: ""
`

Thanks for your help.

**Comment by dnskr** [comment]
Related [PR](https://github.com/jenkinsci/docker/pull/1025) in jenkins docker repository waiting for being merged.

**Comment by dsargent3220** [comment]
@dnskr , I see the above PR got merged and this ticket
https://github.com/jenkinsci/docker/issues/1061 
indicates it should have gotten deployed but it's not clear what versions have this fix.  Does the latest LTS 2.263.3 have it?  If so, how do I supply the values?  I don't see any changes to the Helm chart that allow passing them and it does not appear to automatically pick them from the other half a dozen places we have set them.

**Comment by Cirrith** [comment]
Ran into a similar issue #208. Looking at the PR mentioned it seems like a doc update is required. I was able to spin up Jenkins behind a proxy using the following values.yaml file:
```yaml
controller:
  initContainerEnv:
    - name: JAVA_OPTS
      value: >-
        -Dhttp.proxyHost=192.168.64.1
        -Dhttp.proxyPort=3128
        -Dhttps.proxyHost=192.168.64.1
        -Dhttps.proxyPort=3128
  containerEnv:
    - name: http_proxy
      value: "http://192.168.64.1:3128"
    - name: https_proxy
      value: "http://192.168.64.1:3128"
  javaOpts: >-
    -Dhttp.proxyHost=192.168.64.1
    -Dhttp.proxyPort=3128
    -Dhttps.proxyHost=192.168.64.1
    -Dhttps.proxyPort=3128
```

I'm not sure about other use cases for these variables but I see potential for aligning everything behind a single variable, especially cause the entire process seems to utilize Java now (init, config, jenkins).
