### ISSUE TITLE
Installing plugins in air-gapped environment

### ISSUE THREAD

**Issue by erezo9** [jenkinsci/helm-charts#166]
Hi,
What is the best solution to install plugins in an air gapped environment?
should I just create my own image with my own plugins
or is there a way to give Jenkins a repository where it can grab all the plugins (like artifactory)

**Comment by torstenwalter** [comment]
I think it's best to build an image with pre-installed plugins. That also removes run time dependency to plugin site.

**Comment by fl-max** [comment]
You set the env var to control this:
```yaml
  initContainerEnv:
    - name: JENKINS_UC_DOWNLOAD
      value: "https://www.example.com/repository/jenkins-download"
```
