### ISSUE TITLE
Plugin installation working?

### ISSUE THREAD

**Issue by djtecha** [jenkinsci/helm-charts#173]
Is it me or does plugin installation as code just not work? Trying to install via helm like this

```
controller:
  jenkinsAdminEmail: vim@example.com
  installPlugins:
    - simple-theme-plugin:0.6
  initializeOnce: true
  sidecars:
    configAutoReload:
      enabled: true
```

And it doesn't install at all. Looking at the logs I see this with no followup info

[2020-12-04 02:53:13] POST request sent to http://localhost:8080/reload-configuration-as-code/?casc-reload-token=jenkins-0. Response: 500 Server Error

**Comment by dduportal** [comment]
Hi @djtecha , I might be saying something wrong,  but can you try to add the `rbac` section to enable the feature as described in https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/README.md#config-as-code-with-or-without-auto-reload please?

If it still does not work, do you mind sharing the commands and logs you used to retrieve the pods status and logs?

**Comment by torstenwalter** [comment]
@djtecha You are just installing simple theme plugin and nothing else. In that case kubernetes and configuration-as-code plugin are missing and the sidecar container is not able to reload the configuration.

**Comment by dduportal** [comment]
For information, the PR #207 had updated the documentation at https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/README.md#consider-using-a-custom-image to explain a bit more this requirement. Hope it helps.

**Comment by djtecha** [comment]
I'll give these a go and update the helm chart version to take in that PR. But the side car was working just fine in my current config and some plugins would appear to work while others would result in a 500 error from the CaC pod.

**Comment by djtecha** [comment]
Still running into problems on 3.0.14 figured I'd post my whole config here

```
rbac:
  create: true

controller:
  jenkinsAdminEmail: storesre@test.com
  additionalPlugins:
    - simple-theme-plugin:0.6
  initializeOnce: false
  sidecars:
    configAutoReload:
      enabled: true
  JCasC:
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to the Staging Jenkins.
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-group
                operator: In
                values:
                  - jobs
  tolerations:
    - key: dedicated
      operator: Equal
      value: jobs
  containerEnv:
    - name: DATADOG_JENKINS_PLUGIN_TARGET_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP


agent:
  enabled: true
  podRetention: "Never"
  idleMinutes: 5
  podName: "jenkins-executor"
  namespace: jenkins
  workspaceVolume:
    type: PVC
    claimName: "efs-jenkins-claim"
    readOnly: false
  yamlTemplate: |-
    apiVersion: v1
    kind: Pod
    spec:
      tolerations:
      - key: dedicated
        operator: Equal
        value: jobs
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-group
                    operator: In
                    values:
                      - jobs
  podTemplates:
    awscli: |
      - name: awscli
        label: awscli
        namespace: jenkins
        inheritFrom: "jenkins-executor"
        yamlMergeStrategy: merge
        serviceAccount: jenkins
        showRawYaml: true
        containers:
          - name: amazon
            image: amazon/aws-cli:latest
            command: "/bin/sh -c"
            args: "cat"
            ttyEnabled: true
            privileged: true
            resourceRequestCpu: "400m"
            resourceRequestMemory: "512Mi"
            resourceLimitCpu: "1"
            resourceLimitMemory: "1024Mi"

persistence:
  enabled: true
  existingClaim: efs-jenkins-claim

service:
  portName: http
  labels:
    app: jenkins
```
