### ISSUE TITLE
Why do we need secrets-dir empty volume?

### ISSUE THREAD

**Issue by torstenwalter** [jenkinsci/helm-charts#19]
I am wondering why we actually need the `secrets-dir` empty volume.

It's used in the deployment like this:

```
      initContainers:
        - command:
          ...
          volumeMounts:
            ...
            - mountPath: /usr/share/jenkins/ref/secrets/
              name: secrets-dir
      containers:
        - name: jenkins
         ....
          volumeMounts:
            ...
            - mountPath: /usr/share/jenkins/ref/secrets/
              name: secrets-dir
              readOnly: false
      volumes:
      ...
      - name: secrets-dir
        emptyDir: {}
```

The only place I find where this is used is in
