### ISSUE TITLE
Cloud config - Amazon EC2 possibility

### ISSUE THREAD

**Issue by nickjmv** [jenkinsci/helm-charts#197]
Hi,

We are looking into your chart to move our Jenkins setup to EKS on AWS. While being able to successfully deploy a clean Jenkins we came to conclusion there was no option to define another cloud configuration than the preconfigured Kubernetes cloud config as this is hardcoded in the _helpers.tpl file.

Is there a specific reason why there is no option to configure an Amazon EC2 cloud configuration template? Or is this on the roadmap to let users like us configure another cloud config?

Kind regards.

**Comment by torstenwalter** [comment]
Hi, this chart intend to run Jenkins running on Kubenretes and to also schedule agent on Kubernetes.

It also allows to configure everything which can be configured using JCasC via `controller.JCasC.configScripts`
See: https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins#configuration-as-code

For AWS you might be interested in https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/ec2.
There is nothing against adding native support for it in the chart. So far nobody create a PR for it.

**Comment by jchenrev** [comment]
The problem I see in this case is I cannot put my other cloud backend config in a separate jcasc config file, with the default jcasc enabled.

It will cause a 
```
java.lang.IllegalArgumentException: Single entry map expected to configure a hudson.slaves.Cloud
```

But a work around is to use configScripts, which will declare the other cloud backend config in default jcasc config file.

**Comment by jchenrev** [comment]
Actually, the `configScripts` is generating a separate config file as well, which still has the same error

```
jenkins:
  controller:
    JCasC:
      configScripts:
          clouds: |-
            jenkins:
              clouds:
              - amazonEC2:
                cloudName: ec2
                region: us-west-2
                sshKeysCredentialsId: jenkins-slave-ssh
                templates:
                  ami: ...
```

**Comment by jchenrev** [comment]
> Actually, the `configScripts` is generating a separate config file as well, which still has the same error
> 
> ```
> jenkins:
>   controller:
>     JCasC:
>       configScripts:
>           clouds: |-
>             jenkins:
>               clouds:
>               - amazonEC2:
>                 cloudName: ec2
>                 region: us-west-2
>                 sshKeysCredentialsId: jenkins-slave-ssh
>                 templates:
>                   ami: ...
> ```

my bad it's actually my yaml is wrong, the correct one should be

```
jenkins:
  controller:
    JCasC:
      configScripts:
          clouds: |-
            jenkins:
              clouds:
              - amazonEC2:
                  cloudName: ec2
                  region: us-west-2
                  sshKeysCredentialsId: jenkins-slave-ssh
                  templates:
                    ami: ...
```

Note the indentation after `amazonEC2`. This will still create a separate jscac config file, but jenkins will load it fine (it will merge into the array of `jenkins.clouds` where default `kubernetes` settings are already in it.

Sorry for the spammy comments above.
