### ISSUE TITLE
wrong ingress v1 structure

### ISSUE THREAD

**Issue by matihost** [jenkinsci/helm-charts#198]
Commit https://github.com/jenkinsci/helm-charts/commit/382e3278f77f9c5a65d0fe0b6be389aef4b33fb3 and 
https://github.com/jenkinsci/helm-charts/blob/382e3278f77f9c5a65d0fe0b6be389aef4b33fb3/charts/jenkins/templates/jenkins-controller-secondary-ingress.yaml#L4

leads to error:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]
```

Switching only ingress api version to v1  is not enough to migrate to Ingress v1. Ingress v1 structure is not compatible with v1beta1, hence this commit makes chart not working with K8S 1.19.0 +

Fallback to chart 3.0.9 works.

**Comment by garethjevans** [comment]
I'm hoping that https://github.com/jenkinsci/helm-charts/pull/200 may assist here, I'm just working on a test environment to try and validate this.

**Comment by garethjevans** [comment]
@matihost do you have some extra config around ingresses (like a context path) that I can use to test out these changes?

**Comment by lybaokhanh** [comment]
I got the same error when running Kubernetes 1.19.3 on my local machine.

Ingress configuration:
```
ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      path: "/jenkins"
    hostName: jenkins.domain.com
```

A temporary solution which can solve the problem is custom `paths` on configuration:
```
ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      path: "/jenkins"
    hostName: jenkins.domain.com
    paths:
      - path: "/jenkins"
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080
```
