### ISSUE TITLE
init container - jenkins-plugin-cli problem

### ISSUE THREAD

**Issue by Hokwang** [jenkinsci/helm-charts#208]
Hi, please look at https://github.com/jenkinsci/docker/issues/1061

before chart version 3.0, there was no problem.
I can set http_proxy env and init container works.

from 3.0, jenkins-plugin-cli used, and it need to set JAVA_OPTS.
But, current latest lts docker image does not use this env.

before the next lts image release,
I, in proxy env., can't use this chart properly.

**Comment by Cirrith** [comment]
I tried going back to chart version 2.19.0 with it's image tag of 2.249.3 and was still seeing the issue, so I don't think it is directly tied to the 3.0.0 chart update. I found you can disable the use of **jenkins-plugin-cli** in the init image by setting the following value:
```yaml
controller:
  jenkinsWar: ""
```

This value is only used by the **jenkins-plugin-cli** so it seems to be an easy way of disabling the new method until it is updated to handle proxy info.

**Comment by Hokwang** [comment]
@Cirrith Thanks for your comment!

**Comment by Cirrith** [comment]
@Hokwang Why did you close this issue? I would like to see it remain open until a solution is put into place, I only recommended a work around.

**Comment by Hokwang** [comment]
@Cirrith You mentioned how to avoid using `jenkins-plugin-cli` and I think it is OK to me for now and new lts docker image will release soon.

**Comment by j005u** [comment]
Another option is to add the following to initContainerEnv:
```
- name: JAVA_TOOL_OPTIONS
  value: '-Dhttp.proxyHost=192.168.0.13 -Dhttp.proxyPort=8080 -Dhttps.proxyHost=192.168.0.13 -Dhttps.proxyPort=8080 -Dhttps.nonProxyHosts="kubernetes.default|*.cluster.local" -Dhttp.nonProxyHosts="kubernetes.default|*.cluster.local"'

```
Then jenkins-plugin-cli behaves correctly. An update to the README would be appreciated until javaOpts is exposed for the init cointainer as well.

**Comment by Hokwang** [comment]
@j005u yeah, I know there's a using `JAVAOPTS` way after container and jenkins-plugin-cli updates. but I am using still old way.
```
initContainerEnv:
    - name: http_proxy
      value: "http://1.2.3.4:8080"
    - name: https_proxy
      value: "http://1.2.3.4:8080"
    - name: CURL_OPTIONS
      value: "-sSLk --ignore-content-length"
    - name: CURL_CONNECTION_TIMEOUT
      value: "50"
    - name: CURL_RETRY_DELAY
      value: "5"
```
and I will tell you one more thing, there's no `Dhttps.nonProxyHosts` option. `Dhttp.nonProxyHosts` works for http/https both.
