### ISSUE TITLE
Permission denied on disable Setup Wizard step

### ISSUE THREAD

**Issue by pete-by** [jenkinsci/helm-charts#210]
I use https://www.jenkins.io/doc/book/installing/kubernetes/ as the guide as well as yaml files for Service Account, Volume and config values.

After running `helm install jenkins -n jenkins -f jenkins-values.yaml jenkinsci/jenkins`

Pod is failing to proceed to Ready state:
```
kubectl logs -n jenkins jenkins-0 -c init
disable Setup Wizard
/var/jenkins_config/apply_config.sh: 4: /var/jenkins_config/apply_config.sh: cannot create /var/jenkins_home/jenkins.install.UpgradeWizard.state: Permission denied
```

**Version of Helm and Kubernetes**:

Helm Version: v3.4.2

Kubernetes Version: v1.17.0 on minikube

**Which version of the chart**: 3.0.14

**What happened**:

Jenkins pod is not initialized and Jenkins container is not starting.

**What you expected to happen**:

Jenkins pod up and running

**How to reproduce it** (as minimally and precisely as possible):

Follow the steps from the user handbook.

_jenkins-sa.yaml:_
```
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: jenkins
    namespace: jenkins
...
```
_values.yaml:_
```
storageClass: jenkins-pv
...
serviceType: NodePort
nodePort:32000
...
serviceAccount:
  create: false
  # The name of the service account is autogenerated by default
  name: jenkins
  annotations: {}
```

**Workaround**:

setting `runAsUser: 0` resolves the issue.

**Comment by torstenwalter** [comment]
Did you try the installation instructions in the README of this repository?

**Comment by pete-by** [comment]
> Did you try the installation instructions in the README of this repository?

I made several attempts by launching a separate minikube cluster, adding namespace, and then installing with basic

`helm install -n jenkins jenkins-release jenkinsci/jenkins`

but jenkins pod could never start because of OOM and eventually minikube crashed too:

```
State:              Waiting
      Reason:       CrashLoopBackOff
Last State:         Terminated
      Reason:       Error
      Exit Code:    137
```
```
16m         Normal    Starting                  node/minikube   Starting kubelet.
16m         Warning   SystemOOM                 node/minikube   System OOM encountered, victim process: java, pid: 9661
16m         Warning   SystemOOM                 node/minikube   System OOM encountered, victim process: java, pid: 11078
16m         Warning   SystemOOM                 node/minikube   System OOM encountered, victim process: java, pid: 13121
16m         Warning   SystemOOM                 node/minikube   System OOM encountered, victim process: java, pid: 15717
16m         Normal    NodeHasSufficientMemory   node/minikube   Node minikube status is now: NodeHasSufficientMemory
16m         Normal    NodeHasNoDiskPressure     node/minikube   Node minikube status is now: NodeHasNoDiskPressure
16m         Normal    NodeHasSufficientPID      node/minikube   Node minikube status is now: NodeHasSufficientPID
16m         Normal    NodeNotReady              node/minikube   Node minikube status is now: NodeNotReady
16m         Normal    NodeAllocatableEnforced   node/minikube   Updated Node Allocatable limit across pods
15m         Normal    NodeReady                 node/minikube   Node minikube status is now: NodeReady
14m         Warning   SystemOOM                 node/minikube   System OOM encountered, victim process: java, pid: 19523
```

I tried starting the cluster with --memory=8192  --memory=16384 (32G total on my machine) but with the same outcome.

**Comment by pete-by** [comment]
It seems the memory arguments did not apply after restarting the cluster and the initial 2G were used. I checked Hyper-V manager settings for the cluster and changed the assigned memory for the VM to 8G, that helped to resolve the original issue. I am thus closing the bug.

**Comment by survivant** [comment]
Workaround:

setting runAsUser: 0 resolves the issue.

**Comment by cmoulliard** [comment]
Using `runAsUSer: 0` raises this error using kubernetes 1.18 --> `Error: container's runAsUser breaks non-root policy`

**Comment by v1v** [comment]
I'm seeing this issue too after using the proposal to speedup the PVC:
-  https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/README.md#long-volume-attachmount-times
```
  podSecurityContextOverride:
    runAsNonRoot: true
    runAsUser: 1000
    supplementalGroups: [1000]
```

with the version `3.3.3`

**Comment by sreejith421** [comment]
disable Setup Wizard
/var/jenkins_config/apply_config.sh: 4: cannot create /var/jenkins_home/jenkins.install.UpgradeWizard.state: Permission denied
Both not fixing the issue runAsUser: 0
podSecurityContextOverride:
    runAsNonRoot: true
    runAsUser: 1000
    supplementalGroups: [1000]

**Comment by sagron** [comment]
I fixed by adding gid annotation to jenkins-volume.yaml:
`apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  storageClassName: jenkins-pv
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-volume/`

**Comment by js-timbirkett** [comment]
I'm not sure that any of the suggestions above actually work... it's more likely that the `chown` the kubelet was doing finished. Anyways, if you can deal with the time for the initial `chown` to complete and you're on Kubernetes 1.20+, set this:
```
  podSecurityContextOverride:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
 ```
 
 and in theory, it will only `chown` if the root directory permissions are mismatched: https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/#allow-users-to-skip-recursive-permission-changes-on-mount

**Comment by plentifullee** [comment]
2022, still able to reproduce this bug...

**Comment by omerbsezer** [comment]
On each worker node, mount and give permissions, so the containers on the worker nodes can easily reach the NFS, this will solve the permission problem. 

```
sudo apt install nfs-common
sudo apt install cifs-utils
sudo mkdir /data                                     # we'll create /data directory under root and mount it to NFS
sudo mount -t nfs IP:/share /data/          # /share directory is created while creating NFS server
sudo chmod 777 /data                            # give permissions
```

**Comment by KeHaohaoke** [comment]
> 2022, still able to reproduce this bug...

Did you solve it according to the method mentioned in the discussion? Set runuser and so on.

**Comment by unacceptable** [comment]
> Did you solve it according to the method mentioned in the discussion? Set runuser and so on.

I did to no avail.  Here's a snippet from my helmfile:

```
  values:
  - persistence:
      storageClass:
      annotations:
        pv.beta.kubernetes.io/gid: "1000"
    controller:
      podSecurityContextOverride:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      tag: 2.350-jdk11
```

I don't wan to run as `root`, and I have also tried `Always` for the `fsGroupChangePolicy`.

**Comment by KeHaohaoke** [comment]
> > Did you solve it according to the method mentioned in the discussion? Set runuser and so on.
> 
> I did to no avail. Here's a snippet from my helmfile:
> 
> ```
>   values:
>   - persistence:
>       storageClass:
>       annotations:
>         pv.beta.kubernetes.io/gid: "1000"
>     controller:
>       podSecurityContextOverride:
>         runAsUser: 1000
>         runAsGroup: 1000
>         runAsNonRoot: true
>         fsGroup: 1000
>         fsGroupChangePolicy: "OnRootMismatch"
>       tag: 2.350-jdk11
> ```
> 
> I don't wan to run as `root`, and I have also tried `Always` for the `fsGroupChangePolicy`.

I've done some tests. If it's the minikube/kind way, you need to create the required directory in docker of minikube/kind in advance, and chown -R 1000:1000 dir_name. That's it.

**Comment by unacceptable** [comment]
Looking at this more I realized that the issue was with the underlying node.  A node's disk had filled up so the emptyDir volume mounts would throw generic IO errors.  I found this out when creating a new pod in the cluster based on the template of the StatefulSet after setting the replicas to 0 manually (so that the new pod could mount the ReadWriteOnce volume).

The before mentioned `chown` makes no sense if the pod is crashing during init as you won't have time to do the aforementioned `chown`.  If you suspect that this is an issue then IMHO the easiest way to troubleshoot this and remediate it would be to:
1. set replicas to 0 in the StatefulSet
2. create a new pod with the applicable volume mounts
3. `chown` the directories
4. Delete the new pod
5. Scale replicas back to 1 in the StatefulSet

**Comment by teabolt** [comment]
> I've done some tests. If it's the minikube/kind way, you need to create the required directory in docker of minikube/kind in advance, and chown -R 1000:1000 dir_name. That's it.

This solution worked for me when running on a kind cluster. I had to exec into the kind container and then do `chown -R 1000:1000 /data/jenkins-volume/`. After re-creating the pod jenkins came up successfully.

**Comment by wzprichardwzp** [comment]
It seems like this issue is indeed mentioned in the tutorial, as in we need to do `minikube ssh` then run `sudo chown -R 1000:1000 /data/jenkins-volume`

I do wish that is placed in sequential order in more obvious font, instead of in an info block right under **create persistent volume**. Since there's this many people having trouble with it, this might be a good thing to add.

**Comment by psimms-r7** [comment]
Recently added this - https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/README.md#long-volume-attachmount-times

and now I am seeing this with fresh deploys - can we reopen this issue?

**Comment by kimsehwan96** [comment]
I solved this problem with simply adding `fsGroup` key, value in helm value in `podSecurityContextOverride`

This is the default helm values for jenkins

```
  podSecurityContextOverride:
    runAsUser: 1000
    runAsNonRoot: true
    supplementalGroups: [1000]
```

There is no `fsGroup` key, value so when jenkins initialized, init container doesn't have permission for that volume (persistence)

So I added the `fsGroup` like below

```
        podSecurityContextOverride:
          runAsUser: 1000
          fsGroup: 1000
          runAsNonRoot: true
          supplementalGroups: [1000]
```
