### ISSUE TITLE
Update fails because chart attempts to update the clusterip that's been set by kubernetes.

### ISSUE THREAD

**Issue by blongman-snapdocs** [jenkinsci/helm-charts#214]
**Describe the bug**
When updating the installed helm chart (with terraform on EKS version of k8s) it fails due to the following error:

```
Error: failed to replace object: Service "jenkins-agent" is invalid: spec.clusterIP: Invalid value: "": field is immutable && failed to replace object: Service "jenkins" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

I've found a relevant description of the error here - https://github.com/helm/helm/issues/6378#issuecomment-557746499

And the code that seems like it should work is here - https://github.com/jenkinsci/helm-charts/blob/c00b41ac73c89ce17c48ac787341e3d5cbfc80b8/charts/jenkins/templates/jenkins-controller-svc.yaml#L21-L24

**Version of Helm and Kubernetes**:

Helm Version:

```console
 $ helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

Kubernetes Version:

```console
 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
Tried on 3.0.14 and 3.0.12

**What happened**:
Had to taint the resource in terraform so it would be destroyed and recreated.

**What you expected to happen**:
It to update the chart with new values.

**How to reproduce it** (as minimally and precisely as possible):

values.yaml (only put values which differ from the defaults)

Don't define clusterIP or define it as null.

**Anything else we need to know**:
Ask me questions.  Happy to troubleshoot.

**Comment by torstenwalter** [comment]
Which values are you setting?

**Comment by blongman-snapdocs** [comment]
Scrubbed a little and leaving out the plugins and JcasC:

```
controller:
  image: accountnumber.dkr.ecr.us-west-2.amazonaws.com/jenkins
  tag: 2.263.1
  resources:
    requests:
      cpu: "2"
      memory: "8Gi"
    limits:
      cpu: "2"
      memory: "8Gi"
  clusterIP: null
  nodeSelector:
    autoscaling: "false"
    topology.kubernetes.io/zone: us-west-2b
  containerEnv:
    - name: CASC_VAULT_KUBERNETES_ROLE
      value: "jenkins"
    - name: CASC_VAULT_URL
      value: "https://vault.${hostname}"
    - name: CASC_VAULT_PATHS
      value: "secret/cicd/jenkins/master.env,secret/cicd/jenkins/${env}.env"
  serviceType: "NodePort"
  ingress:
    enabled: true
    hosts:
      - ${hostname}/*
    extraPaths:
      - path: /*
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
      - path: /
        backend:
          serviceName: blue-ocean
          servicePort: use-annotation
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/success-codes: 200,403
      alb.ingress.kubernetes.io/certificate-arn: "${ssl-cert}"
      alb.ingress.kubernetes.io/scheme: "internet-facing"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/actions.blue-ocean: '{"Type": "redirect","RedirectConfig":{"Protocol":"HTTPS","Port":"#{port}","Host": "#{host}","Path": "/blue/pipelines/","Query":"#{query}","StatusCode":"HTTP_301"}}'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":{ "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/security-groups: "${extra-security-groups}"
      alb.ingress.kubernetes.io/ssl-policy: "${ssl-negotiation-policy}"
      external-dns.alpha.kubernetes.io/hostname: "${hostname}"
  sidecars:
    configAutoReload:
      enabled: true
  overwritePlugins: true
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "${svc-acct-role-arn}"
persistence:
  enabled: true
  existingClaim: jenkins-ebs-claim
```
