### ISSUE TITLE
Overriding agent.containerCap within an additional agent does not limit the number of concurrent replicas of an agent template that can be running

### ISSUE THREAD

**Issue by wejrox** [jenkinsci/helm-charts#251]
**Describe the bug**
Overriding `agent.containerCap` within an additional agent is not applied. 

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
3.1.9

**What happened**:
I created an agent, and extended the agent into multiple additional agents. I added a field entry into my additional agent definition to override the number of replicas of this agent to be possible to create. Upon deployment, I triggered more builds than the number I specified. All of those builds executed concurrently.

**What you expected to happen**:
The builds should queue up once they reach the container cap for the target agent. There is an option within the kubernetes cloud tool configuration area within the Jenkins UI called concurrency limit, but it is empty for my additional agent entry.

**How to reproduce it** (as minimally and precisely as possible):

values.yaml (only put values which differ from the defaults)
```yaml
agent:
  enabled: true

additionalAgents:
  agent-one:
    podName: "agent-one"
    customJenkinsLabel: "agent-one"
    containerCap: 1
  agent-two:
    podName: "agent-two"
    customJenkinsLabel: "agent-two"
    containerCap: 2
```

```
helm install my-release jenkins/jenkins --version 3.1.9 --values values.yaml
```

Navigate to the Jenkins UI, create a scripted pipeline containing a generic job which requires `agent-one`. e.g.
```groovy
node("agent-one") {
  stage("Executing on an agent") {
    sleep(50000)
  }
}
```
Trigger the job more than the container cap specified. In this case, trigger it 2 times.
Within the UI, view the executors present on the left pane. There will be 3 executors present, when there should be 2 executors.

**Anything else we need to know**:
I should mention that I couldn't find sufficiently explanatory documentation for the `containerCap` property. I'm presuming that it is an indication of how many agents of the specified template can exist at a time. If that is not the case, is there an alternative to achieve that functionality? I wish to limit the number of executors matching certain labels that are able to be started due to resource requirements and build concurrency issues.

**Comment by wejrox** [comment]
I've done a bit of digging, and can see that the container cap is only being set to the value of whatever is in the base agent definition.

It is defined [here](https://github.com/jenkinsci/helm-charts/blob/85c304950a6f85aab0e39da7e3aee299fdeaa422/charts/jenkins/templates/_helpers.tpl#L122) that `containerCapStr` is set to `.Values.agent.containerCap` as a string, but further down the overrides for additional templates [perform a simple merge](https://github.com/jenkinsci/helm-charts/blob/85c304950a6f85aab0e39da7e3aee299fdeaa422/charts/jenkins/templates/_helpers.tpl#L161) which will not apply `containerCap` to anything, since the property name is incorrect (since [what the template wants](https://www.jenkins.io/doc/pipeline/steps/kubernetes/#podtemplate-define-a-podtemplate-to-use-in-the-kubernetes-plugin) is `instanceCap`). 

I have attempted to manually define `instanceCap` within an additional agent, but the setting is not applied. This is presumably because the [gotemplate defined](https://github.com/jenkinsci/helm-charts/blob/85c304950a6f85aab0e39da7e3aee299fdeaa422/charts/jenkins/templates/_helpers.tpl#L163) does not contain `instanceCap` and so it is never overridden with the new value. 

It seems that there is a flaw in the interpolation here: It assumes that the main agent object has the same member variables as the agent template, which is not the case. There may be a requirement here to redefine how the values are interpolated as a result.

**Comment by wejrox** [comment]
For anyone encountering the same issue, I've been able to use `podTemplates` instead to define my additional agents in a similar amount of code, which although not a fix does provide a workaround. 

e.g.
```yaml
agent:
    enabled: true
    # Name of the template to create using the values specified here.
    podName: "TEMPLATE"
    # The sum of all executor instances cannot exceed this value.
    containerCap: 20
    # Default environment variables to provide to every pod template. Here as an example.
    envVars:
      - name: MY_VARIABLE
        value: "Whatever is the value"
    # Volumes that should exist within each agent template.
    volumes:
      - type: Secret
        defaultMode: 0600
        mountPath: /home/jenkins/my-secret
        secretName: my-secret
    # Fine grained volume overrides that allow for sub-key based mounting. Added to each agent template.
    yamlTemplate: |-
        spec:
          volumes:
          - name: another-secret
            secret:
              secretName: another-secret
              # Decimal notation because even though the docs say it wants octal, it doesn't accept '0600'.
              defaultMode: 384
          containers:
          - name: "jnlp"
            image: "jenkins/inbound-agent"
            tag: "4.6-1"
            volumeMounts:
              # SSH Key. Mounting from sub key allows known-hosts file to exist.
            - mountPath: /home/jenkins/.ssh/id_rsa
              readOnly: true
              name: another-secret
              subPath: id_rsa
    # Any templates which need to have instance caps are currently required to be defined as `podTemplates`.
    # It may be possible to additionally define `additionalAgents` (untested); it's more consistent to define them 
    # all here though.
    podTemplates:
        dual: |
          - inheritFrom: "TEMPLATE"
            label: "dual"
            name: "dual"
            instanceCap: 2
            instanceCapStr: "2"
        restricted: |
          - inheritFrom: "TEMPLATE"
            label: "restricted"
            name: "restricted"
            instanceCap: 1
            instanceCapStr: "1"
        env-vars: |
          - inheritFrom: "TEMPLATE"
            label: "env-vars"
            name: "env-vars"
            envVars:
              - envVar:
                  key: "MY_KEY"
                  value: "my value"
    resources:
        limits:
            # By default, the agent is given a 512m limit of cpu, which is a bit low. Increase so that we can be speedy.
            cpu: 1024m
            # Specify a default that should meet all our needs for nodes.
            # Defined here since to do it at a template level means redefining everything as we would need to change the
            # container specification (containers is an array, which yaml can't override values of).
            # This is the main restriction of using podTemplates.
            memory: 20Gi
```
