### ISSUE TITLE
Jenkins Secondary Ingress paths value is mangled

### ISSUE THREAD

**Issue by Khaeyel** [jenkinsci/helm-charts#264]
**Is your feature request related to a problem? Please describe.**

I've run into an issue with the jenkins-controller-secondary-ingress template, specifically that the paths specified within mangled when run with a helm template command. Line is here:

https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/jenkins-controller-secondary-ingress.yaml#L36

Mangled output:

`path: >-map[backend:map[path:/ serviceName:[serviceName1] servicePort:[servicePort1]]]`

My valuesfile looks like this (this matches the "primary" ingress in format):

```
  secondaryingress:
    enabled: true
    hostname: [value1]
    annotations:
      kubernetes.io/ingress.class: "nginx-internal"
      external-dns.alpha.kubernetes.io/hostname: [value2]
    paths:
    - backend:
        serviceName: [serviceName1]
        servicePort: [servicePort1]
      path: /
```

With the range and path variable as it is, the `{{ . | quote }}` is interpreted as a whole object, which is invalid. To use my valuesfile as is, I needed to change the variable lookup to `{{ .path | quote }}`

I had similar issues with the lines asking for `$serviceName` and `$servicePort`, because I had to change them from looking up a value I did not want to one that I did specify

**Describe the solution you'd like**

There appears to be very sparse documentation on how to use this, and the default `values.yaml` section for secondaryingress implies that its values should be structured similarly to the "primary" ingress'. Additionally, the templates for the ingresses handle the paths field very differently. I would like to see a standard way to utilize the secondary ingress without having to make template modifications to it

**Additional context**

I'm setting up Jenkins within a Kubernetes cluster and attempting to connect an external slave/worker to it. The issue is that Jenkins lies behind a Nginx Ingress Controller, which means if I need to have a secondary ingress to handle traffic coming on on the JNLP port (50000) since it uses the same paths that a normally functioning jenkins uses (/).
