### ISSUE TITLE
Reloading configuration not possible with helm when not using autoreload

### ISSUE THREAD

**Issue by oolfloo** [jenkinsci/helm-charts#269]
Hi, 

I think I noticed unintended behavior, when using this Helm-Chart.

**Describe the bug**

When using the Helmchart with 
```controller:
  sidecars:
    configAutoReload:
      enabled: false
```

there is no easy way of updating the config. 

**Version of Helm and Kubernetes and chart**:
I'm using:
Chart v3.1.3
Helm v3.5.2
Kubectl 1.20.3
K8s 1.17.11 / AKS

**What happened**:

The "apply_config.sh" script, which is used for applying the casc-configs, first checks if it has already run and then skips:
```    
if [ -f /var/jenkins_home/initialization-completed ]; then
      echo "controller was previously initialized, refusing to re-initialize"
      exit 0
    fi
```

That means, when the values file is updated and rolled out vial "helm upgrade", the newly creates JCasC files will never be copied into Jenkins. The only way to enforce an update is the manual deletion of the "initialization-completed" file.

**What you expected to happen**:

In case of configuration update in the values-files and rollout via "helm upgrade", I expect the Jenkins configuration to be updated.

**How to reproduce it** (as minimally and precisely as possible):

values.yaml 

```
controller:
  sidecars:
    configAutoReload:
      enabled: false
  JCasC:
    configScripts:
      common-jenkins: |
        jenkins:
          nodeProperties:
          - authorizationMatrix:
              inheritanceStrategy: "inheritingGlobal"
              permissions:
              - "Agent/Build:ME"
```
helm install my-release jenkins/jenkins --values values.yaml

then change values.yaml to:

```controller:
  sidecars:
    configAutoReload:
      enabled: false
  JCasC:
    configScripts:
      common-jenkins: |
        jenkins:
          nodeProperties:
          - authorizationMatrix:
              inheritanceStrategy: "inheritingGlobal"
              permissions:
              - "Agent/Build:ABC"
```

and upgrade with "helm upgrade my-release jenkins/jenkins --values values.yaml".

The logs of the init container will be "controller was previously initialized, refusing to re-initialize" and no configuration update has been performed.
