### ISSUE TITLE
Default value to .Values.controller.lifecycle for Graceful Shutdown 

### ISSUE THREAD

**Issue by abdennour** [jenkinsci/helm-charts#273]
**Is your feature request related to a problem? Please describe.**
If Jenkins is restarted accidentally, there is no guarantee that it will return back :( 

**Describe the solution you'd like**
I would like to intercept the restart by a safe shutdown (safe exist).
This is can be done using `pod.spec.contianers.lifecycle.preStop` block.

Considering these API calls : 
```sh
$ curl -X POST -u <user>:<password> http://<jenkins.server>/restart
$ curl -X POST -u <user>:<password> http://<jenkins.server>/safeRestart
$ curl -X POST -u <user>:<password> http://<jenkins.server>/exit
$ curl -X POST -u <user>:<password> http://<jenkins.server>/safeExit
$ curl -X POST -u <user>:<password> http://<jenkins.server>/quietDown
$ curl -X POST -u <user>:<password> http://<jenkins.server>/cancelQuietDown
```
Or consider this CLI calls: 

```sh
$ java -jar jenkins-cli.jar -s http://<jenkins-server>/ restart
$ java -jar jenkins-cli.jar -s http://<jenkins-server>/ safe-restart
$ java -jar jenkins-cli.jar -s http://<jenkins-server>/ shutdown
$ java -jar jenkins-cli.jar -s http://<jenkins-server>/ safe-shutdown
$ java -jar jenkins-cli.jar -s http://<jenkins-server>/ quiet-down
$ java -jar jenkins-cli.jar -s http://<jenkins-server>/ cancel-quiet-down
```
You know what ; consider this lifecycle example : 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-demo
spec:
  containers:
  - name: lifecycle-demo-container
    image: nginx
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
      preStop:
        exec:
          command: ["/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done"]
```

Can we apply it and make it like default lifecycle ?

**Describe alternatives you've considered**
Only cloudnative solutions

**Additional context**

- https://support.cloudbees.com/hc/en-us/articles/216118748-How-to-Start-Stop-or-Restart-your-Instance-
- https://medium.com/@0ffset/gracefully-terminating-jenkins-on-kubernetes-16dca364b692
- https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/

**Comment by torstenwalter** [comment]
@abdennour Sounds like a good proposal. Which `<user>:<password>` value do you suggest to use? I think we need an API token here.
As people can configure their own authentication providers there might not be an admin user which is managed by the chart. Should users provide a secret in that case which contains username and api token?

**Comment by abdennour** [comment]
@torstenwalter i got your point. So these API calls requires authentication. I suggest to implement all prerequisites before implementing this feature.
some of these prerequisites are :
- Helm Chart can manage admin token

**Comment by timmjd** [comment]
What you can do to achieve this:
```yaml
---
controller:
  terminationGracePeriodSeconds: 3600
  lifecycle:
    preStop:
      exec:
        command:
        - /bin/bash
        - -c
        - while [ $(curl -s 'http://localhost:8080/computer/api/xml?xpath=//busyExecutors' | sed -r 's/<busyExecutors>(.*)<\/busyExecutors>/\1/g') -ne '0' ]; do sleep 15; done
```

By this, the hock will block for max of `1 hour` or `busyExecutors==0` before sending the SIGTERM. Therefore reboot will be delayed until all jobs have been completed. This also should work without any functional user or token.

The only drawback is the Kubernetes behavior where the ingress will immediately start replying with an 503 due to Kubernetes will stop routing traffic to the pod. Therefore it might look like Jenkins died - but actually it's waiting until it's save to restart.
