### ISSUE TITLE
No way to customize Probe Handler from httpGet to something else ( tpcSocket or exec)

### ISSUE THREAD

**Issue by abdennour** [jenkinsci/helm-charts#276]
**Describe the bug**
if you have this custom values:
```yaml
controller:
  probes:
    livenessProbe:
      tcpSocket:
        port: 8080
```
Then, the computed values will be a merge between default values of the chart + these values which becomes:
```yaml
controller:
  probes:
    livenessProbe:
      httpGet:
        path: /login
        port: http
      tcpSocket:
        port: 8080
```

This is wrong and the statefulset will thru Error in its events 
```
Forbidden: may not specify more than 1 handler type, spec.containers[0].livenessProbe.tcpSocket: Forbidden:
```

**Version of Helm and Kubernetes**:

Helm Version: 

```console
$ helm version
v3.2.4
```

Kubernetes Version:

```console
$ kubectl version
v1.17
```

**Which version of the chart**:
3.1.11

**What happened**:
See first section

**What you expected to happen**:
I expect to be able to totally override `.Values.probes.livenessProbe.httpGet` and `.Values.probes.readinessProbe.httpGet`
**How to reproduce it** (as minimally and precisely as possible):
See first section

**Anything else we need to know**:
