### ISSUE TITLE
ConfigMap for JCasC not being applied

### ISSUE THREAD

**Issue by bigjew92** [jenkinsci/helm-charts#279]
**Describe the bug**
ConfigMaps are being created for JCasC but not being applied within pod. 

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.7-gke.1500", GitCommit:"99f90aac4943d3d1c8d9705458c2711240fcfc2b", GitTreeState:"clean", BuildDate:"2021-02-03T09:17:28Z", GoVersion:"go1.15.5b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**: 3.0.3

**What happened**: ConfigMaps are crated, but not showing up under `/var/jenkins_home/casc_configs/`

**What you expected to happen**: ConfigMaps generating new yaml and that yaml placed within `/var/jenkins_home/casc_configs/` so Jenkins can be configured through code.

**How to reproduce it** (as minimally and precisely as possible):

```
jenkins:
  namespaceOverride: jenkins-mlplatform
  rbac:
    readSecrets: true
  persistence:
    storageClass: standard-rwo
  controller:
...
    installPlugins:
      - git
      - workflow-job
      - kubernetes
      - workflow-aggregator
      - credentials-binding
      - configuration-as-code
    JCasC:
      configScripts:
        welcome-message: |
          jenkins:
            systemMessage: Welcome to ML Platform CI\CD server.  This Jenkins is configured and managed 'as code'.
        ldap-settings: |
          jenkins:
            securityRealm:
              saml:
                advancedConfiguration:
                  forceAuthn: false
                  spEntityId: "Jenkins-users"
                binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                displayNameAttributeName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
                groupsAttributeName: "group"
                idpMetadataConfiguration:
                  period: 0
                  xml: "CHANGE ME"
                maximumAuthenticationLifetime: 86400
                usernameCaseConversion: "none"
```

**Anything else we need to know**:
```
k get cm
NAME                                                           DATA   AGE
kube-root-ca.crt                                               1      18h
mlplatform-jenkins-deployment                                  2      17h
mlplatform-jenkins-deployment-jenkins-config-ldap-settings     1      17h
mlplatform-jenkins-deployment-jenkins-config-welcome-message   1      40m
mlplatform-jenkins-deployment-jenkins-jcasc-config             1      17h
```
```k describe cm mlplatform-jenkins-deployment-jenkins-config-welcome-message
Name:         mlplatform-jenkins-deployment-jenkins-config-welcome-message
Namespace:    jenkins-mlplatform
Labels:       app.kubernetes.io/component=jenkins-controller
              app.kubernetes.io/instance=mlplatform-jenkins-deployment
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=jenkins
              argocd.argoproj.io/instance=mlplatform-jenkins-deployment
              helm.sh/chart=jenkins-3.0.3
              mlplatform-jenkins-deployment-jenkins-config=true
Annotations:  <none>

Data
====
welcome-message.yaml:
----
jenkins:
  systemMessage: Welcome to ML Platform CI\CD server.  This Jenkins is configured and managed 'as code'.
Events:  <none>
```

```
k exec mlplatform-jenkins-deployment-0 -- ls -la /var/jenkins_home/casc_configs/
Defaulting container name to jenkins.
Use 'kubectl describe pod/mlplatform-jenkins-deployment-0 -n jenkins-mlplatform' to see all of the containers in this pod.
total 8
drwxrwsrwx  2 root jenkins 4096 Mar  3 18:59 .
drwxrwsr-x 17 root jenkins 4096 Mar  3 19:00 ..
```
