### ISSUE TITLE
add a simple example for JCasC in the docs

### ISSUE THREAD

**Issue by torstenwalter** [jenkinsci/helm-charts#29]
```yaml
master:
  JCasC:
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to our CI\CD server.

```
