### ISSUE TITLE
Add xml jobs feature back in

### ISSUE THREAD

**Issue by longc** [jenkinsci/helm-charts#296]
**Is your feature request related to a problem? Please describe.**
We have a few xml jobs to be installed in jenkins, apart from CASC jobs, could you add this feature back in?

**Describe the solution you'd like**
It will be good to add something like the following in the "apply_config.sh" script in "config.yaml".
apply_config.sh
```
    {{- if .Values.controller.jobs }}
        echo "copy jobs"
        for job in $(ls /var/jenkins_home/xml_jobs); do mkdir -p /var/jenkins_home/jobs/$job && cp -i /var/jenkins_home/xml_jobs/$job /var/jenkins_home/jobs/$job/config.xml; done
    {{- end }}
```

values.yaml
```
# Jenkins XML job configs to provision
  jobs: {}
  #  test: |-
  #    <<xml here>>
```

**Comment by hazzik** [comment]
Isn't it the same request as #224?

**Comment by longc** [comment]
Yes, it is the same feature request.

**Comment by longc** [comment]
I did a work around to get the xml jobs back to Jenkins.

Create a configmap for the xml jobs.
```
kubectl -n jenkins apply -f jenkins-jobs-config.yaml
```

Example of "jenkins-jobs-config.yaml"
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jobs-config
data:
  <job1>: |-
    <?xml version='1.1' encoding='UTF-8'?>
    <flow-definition plugin="workflow-job">
    ...
  <job2>: |-
    <?xml version='1.1' encoding='UTF-8'?>
    <flow-definition plugin="workflow-job">
    ...
```

Then copy the jobs from the configmap to jenkins job directory by using the values file "jenkins_xml_jobs.yaml".
Example of helm3 installation
```
helm3 upgrade jenkins jenkins/jenkins \
    --install \
    --atomic \
    --wait \
    --timeout 5m \
    --namespace jenkins \
    --version 3.3.18 \
    --set persistence.size=10Gi \
    --set controller.tag=2.295-alpine \
    --set controller.serviceType=ClusterIP \
    --set controller.JCasC.defaultConfig=false \
    --values "./jenkins_xml_jobs.yaml"
```

"jenkins_xml_jobs.yaml"
```
controller:
  customInitContainers: 
  - name: jenkins-xml-jobs-init
    image: busybox:stable
    command: ['/bin/sh', '-c']
    args: [for job in $(ls /var/jenkins_home/xml_jobs); do mkdir -p /var/jenkins_home/jobs/$job && cp -i /var/jenkins_home/xml_jobs/$job /var/jenkins_home/jobs/$job/config.xml; done]
    volumeMounts:
    - name: jenkins-jobs-config
      mountPath: /var/jenkins_home/xml_jobs
      readOnly: true
    - name: jenkins-jobs
      mountPath: /var/jenkins_home/jobs

persistence:
  volumes:
    - name: jenkins-jobs-config
      configMap:
        name: jenkins-jobs-config
    - name: jenkins-jobs
      emptyDir: {}
  mounts:
    - name: jenkins-jobs
      mountPath: /var/jenkins_home/jobs
```

**Comment by js-timbirkett** [comment]
It makes me sad that it got removed :'(

**Comment by longc** [comment]
@js-timbirkett , don't be sad, the above config might remove the job history, I also have another work around which doesn't remove the job history.

Create jenkins-xml-jobs configmap in jenkins namespace
```
kubectl -n <jenkins_namespace> create -f jenkins-xml-jobs.yaml
```

Sample "jenkins-xml-jobs.yaml"
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-xml-jobs
data:
  <job1_name>: |-
    ...
  <job2_name>: |-
    ...
```

Create configuration as code jobs "casc_jobs.yaml" to reference each job.
```
jobs:
  - script: >
      pipelineJob('<job1_name>') {
        description('<job1_description>')
        definition {
          cps {
            sandbox()
            script(new File('/var/jenkins_home/jenkins-xml-jobs/<job1_name>').text)
          }
        }
      }
  - script: >
      pipelineJob('<job2_name>') {
        description('<job2_description>')
        definition {
          cps {
            sandbox()
            script(new File('/var/jenkins_home/jenkins-xml-jobs/<job2_name>').text)
          }
        }
      }
```

Run helm install with "casc_jobs.yaml"
```
helm3 upgrade jenkins jenkins/jenkins \
    --install \
    --atomic \
    --wait \
    --timeout 5m \
    --namespace <jenkins_namespace> \
    --version 3.5.11 \
    --set persistence.size=10Gi \
    --set persistence.volumes[0].name="jenkins-xml-jobs",persistence.volumes[0].configMap.name="jenkins-xml-jobs" \
    --set persistence.mounts[0].name="jenkins-xml-jobs",persistence.mounts[0].mountPath="/var/jenkins_home/jenkins-xml-jobs" \
    --set controller.tag=2.304-alpine \
    --set controller.serviceType=ClusterIP \
    --set controller.JCasC.defaultConfig=false \
    --set-file controller.JCasC.configScripts.jobs="./casc_jobs.yaml"
```

**Comment by js-timbirkett** [comment]
@longc - this is a bit nicer than the addition of `customInitContainers` as mentioned previously. Thanks!

**Comment by zopz** [comment]
I jumped off this @longc's workaround for our implementation, but one small tweak to ensure we retain job history: rather than use an empty volume for the `jenkins-jobs` volume, just use the existing `jenkins-home` volume from the chart's main persistent volume. So it looks like this:

```
   - name: jenkins-xml-jobs-init
      image: "busybox:1.28"
      securityContext:
        runAsUser: 1000
      command: ['/bin/sh', '-c']
      args: [for job in $(ls /var/xml_jobs); do echo "creating $job"; mkdir -p /var/jenkins_home/jobs/$job && cp /var/jenkins_home/xml_jobs/$job /var/jenkins_home/jobs/$job/config.xml; done]
      volumeMounts:
      - name: jenkins-jobs-config
        mountPath: /var/xml_jobs
        readOnly: true
      - name: jenkins-home
        mountPath: /var/jenkins_home
```
