### ISSUE TITLE
document how auto reload of JCasC changes works

### ISSUE THREAD

**Issue by torstenwalter** [jenkinsci/helm-charts#30]

**Comment by larrycai** [comment]
This is a good issue to address this in documentation clearly.

My use case is to install jenkins via helm chart and keep it running like before, and want to configure them manually via GUI, so we disable the sidecar for autoupdate and reuse the pvc like below

````
persistence:
    enabled: true
    storageClass: nfs
    existingClaim: jenkins-nfs-permament
master:
    sidecars:
        configAutoReload:
          enabled: false
````

And we noticed after restart the pod (simulate the crash of jenkins pod), some configurations are reloaded while some are kept, it will be good to let us know the strategy and way to check.

So far it feels if it defines in `$CASC_JENKINS_CONFIG`, it will be reloaded like jobs and system configuration.

But some parts are tricky to understand like

* if I define some job views in `values.yaml`, I can't manually to add new view in jenkins, they will be reset always. 

It is good to see new generated jobs are kept (from seed job or manually added)
