### ISSUE TITLE
Persist job folder only

### ISSUE THREAD

**Issue by jgournet** [jenkinsci/helm-charts#326]
**Is your feature request related to a problem? Please describe.**
I would like my jenkins to persist the $JENKINS_HOME/jobs folder, so I can bake everything else into a base image (ie: all my credentials, plugins ...etc would be baked into a docker image).
That way, I can get:
- a fast start of jenkins (no initialization needed)
- I can even avoid version controlling the plugins: just bake the latest version, and if it fails, use a previous image.
- any changes done manually will be wiped clean (like installing a new plugin or adding a new credential or whatever ...)

**Describe the solution you'd like**
In essence, we could maybe just add an option here:
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/jenkins-controller-statefulset.yaml#L120 , something like:
```
          volumeMounts:
            {{- if .Values.controller.persistJobsOnly }}
            - mountPath: {{ .Values.controller.jenkinsHome }}/jobs
            {{- else }}
            - mountPath: {{ .Values.controller.jenkinsHome }}
            {{- end }}
              name: jenkins-home
```
and then add that option "controller.persistJobsOnly" as a false value by default in values.yaml

**Describe alternatives you've considered**
The only other solution I can think of (disclaimer: I'm just starting with this helm chart) would be to modify the init script to wipe off the jenkins home folder except jobs folder, and copy back from the baked image. But that's ugly, and can't even be done easily since the init script does not have a "insert custom script here" (might be a nice to have too ?)

**Additional context**
I know it can be done for the plugins folder by having the plugins in the image in jenkinsRef folder, and playing with the controller.overwritePlugins and controller.installPlugins variables - but that's only for plugins: I'd like to have that simple new option so that we only persist the jobs folder, and nothing else.

I hope I'm clear enough and that it's not a silly request ;)

**Comment by jgournet** [comment]
Quick update:
I actually found out I can accomplish what I need by:
- setting persistence.enabled to false
- creating myself the mounts:
```
persistence.volumes:
- name: jenkins-jobs
  persistentVolumeClaim:
    claimName: myclaim
persistence.mounts:
- name: jenkins-jobs
  mountPath: /var/jenkins_home/jobs
# and for "complete-ish" documentation, those flags are needed as well to use the plugins from the image
controller.installPlugins = []
controller.overwritePluginsFromImage = ""
controller.overwritePlugins = true
```
So technically, that means this ticket could be closed - but this feels like a workaround/hack, while my proposition would make it a bit cleaner, I think => keeping it open for now
