### ISSUE TITLE
E-Mail notification of Jenkins global Configuration is empty using JCasC key

### ISSUE THREAD

**Issue by cmoulliard** [jenkinsci/helm-charts#340]
## Problem

When we use the following `jcasc` config as documented here: https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/mailer within the helm values file
```
  JCasC:
    mailer: |-
      unclassified:
        mailer:
          smtpHost: smtp.corp.redhat.com
          smtpPort: 25
```
then the Jenkins global Configuration (section E-mail Notification) is empty

What is then wrong with my config ?

**Comment by cmoulliard** [comment]
Fixed using the following syntax. A doc with more examples should better help us ;-)
```
  JCasC:
    configScripts:
      # The line hereafter represents a label.
      # The section to be configured starts at the line after the label with the root element: unclassified
      # followed by the key to be configured (= Jenkins Configuration E-mail notification)
      # see: https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/mailer
      mailer: |
        unclassified:
          mailer:
            smtpHost: smtp.corp.redhat.com
            smtpPort: 25
```
