### ISSUE TITLE
agent merge logic does not properly handle booleans

### ISSUE THREAD

**Issue by wmcdona89** [jenkinsci/helm-charts#35]
the `merge` function does not properly handle booleans as `true` overwrites `false` - see [helm issue 7313](https://github.com/helm/helm/issues/7313) 

[`merge`](http://masterminds.github.io/sprig/dicts.html)
> Merge two or more dictionaries into one, giving precedence to the dest dictionary:

the chart uses `merge` to merge `agent` into `additionalAgents` to ensure they at least have the default values

the following boolean values are impacted:
`agent.privileged`
`agent.alwaysPullImage`
`agent.TTYEnabled`

#### test template
```
{{- range $name, $additionalAgent := .Values.additionalAgents }}
  {{- $additionalAgent := merge $additionalAgent $.Values.agent }}
  {{- $name }}:
  {{- toYaml $additionalAgent | nindent 2 }}
{{- end }}
```
#### values.yaml
```yaml
agent:
  alwaysPullImage: true
  privileged: true
  TTYEnabled: true
additionalAgents:
  maven:
    alwaysPullImage: false
    privileged: false
    TTYEnabled: false
```
### expected result:
```
maven:
  alwaysPullImage: false
  privileged: false
  TTYEnabled: false
````
### actual result:
```
maven:
  alwaysPullImage: true
  privileged: true
  TTYEnabled: true
````

### Fix
using `mergeOverwrite` with `deepCopy` resolves the issue...**but requires helm v2.16.0 and above**
`deepCopy` was added in [sprig v2.22](https://github.com/Masterminds/sprig/blob/master/CHANGELOG.md) which was introduced in [helm v2.16.0](https://github.com/helm/helm/releases/tag/v2.16.0)
`mergeOverwrite` was added in [sprig v2.18](https://github.com/Masterminds/sprig/blob/master/CHANGELOG.md) which was introduced in [helm v2.13.0](https://github.com/helm/helm/releases/tag/v2.13.0)

[`mergeOverwrite`](http://masterminds.github.io/sprig/dicts.html)
> Merge two or more dictionaries into one, giving precedence from right to left, effectively overwriting values in the dest dictionary. This is a deep merge operation but not a deep copy operation. Nested objects that are merged are the same instance on both dicts. If you want a deep copy along with the merge than use the deepCopy function along with merging.

[`deepCopy`](http://masterminds.github.io/sprig/dicts.html)
> The deepCopy function takes a value and makes a deep copy of the value. This includes dicts and other structures.

#### test template
```
{{- range $name, $additionalAgent := .Values.additionalAgents }}
  {{- $additionalAgent := mergeOverwrite (deepCopy $.Values.agent) $additionalAgent }}
  {{- $name }}:
  {{- toYaml $additionalAgent | nindent 2 }}
{{- end }}
```
#### values.yaml
```yaml
agent:
  alwaysPullImage: true
  privileged: true
  TTYEnabled: true
additionalAgents:
  maven:
    alwaysPullImage: false
    privileged: false
    TTYEnabled: false
```
### expected result:
```
maven:
  alwaysPullImage: false
  privileged: false
  TTYEnabled: false
````
### actual result:
```
maven:
  alwaysPullImage: false
  privileged: false
  TTYEnabled: false
````
