### ISSUE TITLE
 additionalExistingSecrets failing ?

### ISSUE THREAD

**Issue by irom77** [jenkinsci/helm-charts#363]
**Describe the bug**
I can't login to jenkins when using Active Directory bind password from existing secret

**Version of Helm and Kubernetes**:

Helm Version: 3

```console
helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

Kubernetes Version:

```console
$kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"4d62230f10af41cec2851b5b113874f6d2098297", GitTreeState:"clean", BuildDate:"2021-03-22T23:01:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:

Latest 83

**What happened**:

Using key ad-password  from existing secret ad-credentials with 
```
 additionalExistingSecrets: 
   - name: ad-credentials
     keyName: ad-password
```
then referencing it in 

```
securityRealm: |-
      activeDirectory:
        domains:
           ...
           bindPassword: ${ad-credentials-ad-password}
```

can't login to jenkins until bind password replaced with string

**What you expected to happen**:

Expect bind password to be taken from secret ad-credentials with key ad-password 

**How to reproduce it** (as minimally and precisely as possible):

```
additionalExistingSecrets: 
   - name: ad-credentials
     keyName: ad-password
JCasC:
  securityRealm: |-
        activeDirectory:
          domains:
             ...
             bindPassword: ${ad-credentials-ad-password}
```

```
helm install my-release jenkins/jenkins --version version --values values.yaml
```

**Anything else we need to know**:

Existing secret

```
kubectl describe secret ad-credentials -n jenkins
Name:         ad-credentials
Namespace:    jenkins
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
ad-password:  17 bytes
ad-username:  17 bytes
```
