### ISSUE TITLE
Custom labels on agent pods

### ISSUE THREAD

**Issue by Sir-Jacques** [jenkinsci/helm-charts#395]
**Is your feature request related to a problem? Please describe.**
We measure resource usage on our clusters using specific pod labels. Currently we can only place this label on the Jenkins master node, but not on the agents it spins up during builds.

**Describe the solution you'd like**
I'd like to be able to specify custom pod labels for agents that use the podTemplate from the values.yaml. I believe this addition would suffice, but please correct me if I'm missing something:
(This snippet is located at charts/jenkins/templates/_helpers.tpl:151)
```
podLabels:
- key: "jenkins/{{ .Release.Name }}-{{ .Values.agent.componentName }}"
  value: "true"
{{- if .Values.agent.customPodLabels }}
{{- range $podLabel := $.Values.agent.customPodLabels }}
- key: {{ required "A customPodLabel key must be provided!" $podLabel.key }}
  value: {{ required "A customPodLabel value must be provided!" $podLabel.value }}
{{- end }}
{{- end }}
```

This way users should be able to add this field to their values.yaml:
```
agent:
  customPodLabels:
  - key: app
    value: jenkins
```

**Extra info**
I've manually added the podLabels in the RELEASE-NAME-jenkins-jcasc-config ConfigMap and this resulted in a working solution (but an out-of-sync ArgoCD application...). I removed all non-related fields from this snippet.
```
jcasc-default-config.yaml: |-
  jenkins:
    clouds:
    - kubernetes:
        podLabels:
          - key: "jenkins/<our_release_name>-jenkins-agent"
            value: "true"
          - key: "app"
            value: "jenkins"
```
