### ISSUE TITLE
podTemplate helper does not allow setting command: "" in container spec

### ISSUE THREAD

**Issue by bartsqueezy** [jenkinsci/helm-charts#432]
**Describe the bug**
Setting the following in `values.yaml`...

```yaml
additionalAgents:
  newagent:
    podName: newagent
    sideContainerName: jnlp
    command: ""
    args: ""
```

Results in the following under <jenkins-url>/configureClouds/

<img width="358" alt="Screen Shot 2021-08-06 at 5 33 20 PM" src="https://user-images.githubusercontent.com/647029/128577132-1fa57e89-5436-4e01-b833-7798400f89fb.png">

As you can see, `Command to run` is being set to `sleep`, when it should be empty.

**Version of Helm and Kubernetes**:

Helm Version: v3.6.1

Kubernetes Version: v1.19.9

**Which version of the chart**: 3.5.9

**What happened**: The `jnlp` container in the pod template has `Command to run` set to `sleep`.

**What you expected to happen**: The `jnlp` container in the pod template should have `Command to run` set to no value/empty string.

**How to reproduce it** (as minimally and precisely as possible):

1. Add the following to your `values.yaml`:
    ```yaml
    additionalAgents:
      newagent:
        podName: newagent
        sideContainerName: jnlp
        command: ""
        args: ""
    ```
2. `helm install`
3. Check `jenkins-jenkins-jcasc-config` ConfigMap value. Verify that `command` is NOT set to an empty string (e.g. `command: `
4. Go https://<jenkins-url>/configureClouds/
5. Expand Pod Template Details for the "newagent" pod template
6. Verify that `Command to run` is set to `sleep`

**Anything else we need to know**:

I think the issue is that the [`jenkins.casc.podTemplate` helper method](https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/_helpers.tpl) is [not wrapping `{{ .Values.agent.command }}` with double quotes](https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/_helpers.tpl#L209) (e.g. `"{{ .Values.agent.command }}"`). I assume this is why setting `command: ""` in `values.yaml` results in `command: ` in the `jenkins-jenkins-jcasc-config` ConfigMap. Additionally, if no value is provided to `command`, [the Kubernetes plugin for Jenkins will default it to `sleep`](https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/resources/org/csanchez/jenkins/plugins/kubernetes/ContainerTemplate/config.jelly#L26).

This issue most notably impacts Windows versions of the `jenkins/inbound-agent` Docker image. The agent process does not properly launch as the default command is set to `sleep`.
