### ISSUE TITLE
Unable to configure jenkins ingress with Traefik 2.5.1

### ISSUE THREAD

**Issue by mokhos** [jenkinsci/helm-charts#455]
So I'm writing this issue after days of manipulating jenkins helm chart values.yaml file! 

I've configured many other apps ingresses(argo-cd, grafana, etc.) via values.yaml in their helm chart. All of them work without any problem. ONLY jenkins doesn't work. Why configuring an ingress in jenkins have to be so complicated????

So the ingress part in my jenkins looks like this:

```
ingress:
    enabled: true
    # Override for the default paths that map requests to the backend
    path: "/jenkins"
    pathType: Prefix
    # - backend:
    #     serviceName: ssl-redirect
    #     servicePort: use-annotation
    # - backend:
    #     serviceName: >-
    #       {{ template "jenkins.fullname" . }}
    #     # Don't use string here, use only integer value!
    #     servicePort: 8080
    # For Kubernetes v1.14+, use 'networking.k8s.io/v1beta1'
    # For Kubernetes v1.19+, use 'networking.k8s.io/v1'
    apiVersion: "networking.k8s.io/v1"
    labels: {}
    annotations:
       traefik.ingress.kubernetes.io/router.entrypoints: web
       traefik.ingress.kubernetes.io/rewrite-target:  /
    ingressClassName: "traefik"
    hostName: jenkins.apps.rancher.example.com 
```

So I even manipulated the "path" many times, I tried even without the rewrite-target. I really am confused!
Would you pleaaase tell me the issue?

Thanks in advance
