### ISSUE TITLE
Agents envVars from secret

### ISSUE THREAD

**Issue by gkocur** [jenkinsci/helm-charts#457]
I need to add some environment variables to agents (k8s pods) which contain some sensitive information (passwords etc.).
I see it's possible to it with Jcasc plugin:

```
envVars:
  - secretEnvVar:
     key: "VAR_NAME"
     optional: true
     secretKey: "PASSWORD"
     secretName: "credentials"
```

I checked in the code and it seems there is no way to do it with helm values since `envVars` list passed to Jcasc plugin is created from `envVars` submitted in values (which has different format though).

From my point of view the simplest way to achieve this is to simply change the format of `envVars` in helm values to align it with format used by Jcasc but this will be incompatible change.

Am I missing something? Is there a way to pass env var from secret to the agents?
