### ISSUE TITLE
Exclude clouds configuration if it's configured as part of JCasC.configScripts

### ISSUE THREAD

**Issue by oleg-z** [jenkinsci/helm-charts#469]
**Is your feature request related to a problem? Please describe.**
Current helm chart assumes kubernetes cloud needs to be configured if deployed on kubernetes. More over cloud is configured even if agent.enabled=false

It may cause issues when additional clouds are required or cloud is configured via different method i.e. via JCasC.configScripts

**Describe the solution you'd like**
Don't configure kubernetes cloud if agent.enabled = false or cloud: is configured as part of JCasC.configScripts (similar to https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/_helpers.tpl#L111)

**Describe alternatives you've considered**
While I can configure cloud in a different way default cloud cause issue when using podInheritence inside of pipeline

**Additional context**

Example of yaml configuration:
```
controller:
 ...
  JCasC:
    configScripts:
      kubernetes-cloud: |
        jenkins:
          clouds:
            - kubernetes:
               <my kubernetes configuration>
agent:
  enabled: false
```
