### ISSUE TITLE
Version 2.6.4 how configuration use the istio-ingressgateway support https ?

### ISSUE THREAD

**Issue by isfong** [jenkinsci/helm-charts#47]
My install command
```shell
helm install -n jenkins-helm jenkins jenkinsci/jenkins \
  --set master.installPlugins="" \
  --set master.imagePullPolicy="IfNotPresent" \
  --set master.javaOpts="-Dhudson.model.DownloadService.noSignatureCheck=true" \
  --set master.jenkinsUrl="jenkins.example.com" \
  --set persistence.size="10Gi"
```

Gateway
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: jenkins-gw
  namespace: jenkins-helm
spec:
  selector:
    app: istio-ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - jenkins.example.com
      tls:
        httpsRedirect: true # sends 301 redirect for http requests
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: tls.jenkins.example.com
      hosts:
        - jenkins.example.com
```

VirtualService
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jenkins-vs
  namespace: jenkins-helm
spec:
  gateways:
    - jenkins-gw
  hosts:
    - jenkins.example.com
  http:
    - route:
        - destination:
            host: jenkins.jenkins-helm.svc.cluster.local
```

At version 2.5.2 it working 
Upgrade the version 2.6.4 it not working
