### ISSUE TITLE
Jenkins pod get OOM

### ISSUE THREAD

**Issue by dsaydon90** [jenkinsci/helm-charts#477]
**Describe the bug**
It seems that the `Jenkins` pod not release back memory to OS and gets OOM (Out of Memory).
I have tried to play a bit with the JAVA_OPTS to force the JVM \ GC to release memory with the following args (multiple variations)
```
controller.javaOpts: "-Xms6144m -Xmx12288m -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxHeapFreeRatio=70 -XX:MinHeapFreeRatio=40"
```
But nothing worked

**Version of Helm and Kubernetes**:

Helm Version: `v3.6.3`

Kubernetes Version: `v1.19.13-eks-8df270`

**Which version of the chart**: `2.303.1`

**How to reproduce it** (as minimally and precisely as possible):

my values (relevant parts):
```
controller:
  resources:
    requests:
      cpu: "1000m"
      memory: "8Gi"
    limits:
      cpu: "4000m"
      memory: "13Gi"
  javaOpts: "-Xms6144m -Xmx12288m -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MaxHeapFreeRatio=70 -XX:MinHeapFreeRatio=40"
  jenkinsOpts: "--sessionTimeout=1440 --sessionEviction=43200"
  initializeOnce: true  
  sidecars:
    configAutoReload:
      enabled: false  
  agent:
      enabled: false
  probes:
    livenessProbe:
      failureThreshold: 10
      periodSeconds: 15
      timeoutSeconds: 10
    readinessProbe:
      failureThreshold: 10
      periodSeconds: 15
      timeoutSeconds: 10
    startupProbe:
      periodSeconds: 15
      timeoutSeconds: 10
  installPlugins: []
```
run jobs until you will get OOM from the `jenkins` pod

**Anything else we need to know**:

kubectl top pod output
```
NAME                              CPU(cores)   MEMORY(bytes)   
jenkins-0                         18m          12475Mi 
```

jenkins monitor plugin
![image](https://user-images.githubusercontent.com/22152786/136410730-a8f518f5-3b36-412d-a5d6-0e3d0d5b2878.png)

After running the `Execute the garbage collector` from the `monitoring` plugin, the JVM released the memory back to the OS
```
NAME                              CPU(cores)   MEMORY(bytes)   
jenkins-0                         8m           7748Mi 
```

**Comment by angelabad** [comment]
Same problem here with minikube

**Comment by dsaydon90** [comment]
I have workaround this:
https://issues.jenkins.io/browse/JENKINS-66561

**Comment by yuezhuangshi** [comment]
Same problem here. 
Java heap was only used about 30%, but it was killed by kubernetes because of OOMKilled(ExitCode = 137)

### Version of Helm and Kubernetes:

Helm Version: v3.4.2

Kubernetes Version: v1.16.6

Which version of the chart: 3.4.0

### Values (relevant parts):

```
controller:
  resources:
    requests:
      cpu: 4000m
      memory: 4Gi
  limits:
      cpu: 4000m
      memory: 4Gi
  javaOpts: >-
    -XX:InitialRAMPercentage=25.0 -XX:MaxRAMPercentage=80.0 -XX:MaxMetaspaceSize=256M
    -XX:+UseG1GC -XX:+UseStringDedeplication -XX:+AlwaysPreTouch
```

I've been stuck with this problem for a long time, any help is appreciated.
