### ISSUE TITLE
EFS volume is not mounted in jenkins pod on AWS EKS

### ISSUE THREAD

**Issue by kafteji** [jenkinsci/helm-charts#489]
**Describe the bug**
Jenkins is not using the persistence volume claim predefined for a static provisioned EFS volume.
It creates its own pv and pvc 

**Version of Helm and Kubernetes**:

Helm Version:

```console
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

Kubernetes Version:

```console
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"archive", BuildDate:"2021-03-30T00:00:00Z", GoVersion:"go1.16", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
```console
version: 3.8.3
```

**What happened**:
Jenkins is not mounting the shared EFS file system

**What you expected to happen**:
jenkins using the EFS filesystem as its persistence volume

**How to reproduce it** (as minimally and precisely as possible):
1. deploy the EFS 
```terraform
resource "aws_efs_file_system" "jenkins_shared_file_system" {
  creation_token   = "Jenkins shared file system"
  performance_mode = "generalPurpose"
  throughput_mode  = "bursting"
  encrypted        = true
  tags             = {
    Name = "Jenkins shared file system"
  }
}

resource "aws_efs_mount_target" "jenkins_efs_private_subnet_1_mount_target" {
  file_system_id  = aws_efs_file_system.jenkins_shared_file_system.id
  subnet_id       = aws_subnet.ci_cd_private_subnet_1.id
  security_groups = [aws_security_group.jenkins_efs_sg.id]
}

resource "aws_efs_mount_target" "jenkins_efs_private_subnet_2_mount_target" {
  file_system_id  = aws_efs_file_system.jenkins_shared_file_system.id
  subnet_id       = aws_subnet.ci_cd_private_subnet_2.id
  security_groups = [aws_security_group.jenkins_efs_sg.id]
}

resource "aws_efs_access_point" "jenkins_efs_access_point" {
  file_system_id = aws_efs_file_system.jenkins_shared_file_system.id
  tags = {
    Name = "Jenkins EFS access point"
  }
  posix_user {
    gid = 1000
    uid = 1000
  }
  root_directory  {
    path          = "/jenkins"
    creation_info  {
      owner_uid   = 1000
      owner_gid   = 1000
      permissions = 777
    }
  }
}

```
2. Deploy the Amazon CSI Driver as described here https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html

3. create the sc, pv and pvc for jenkins (make sure to use the right fs-id and fsap-is)
```yml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-12345::fsap-12345

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi

```
 4. Install the chart with the following configs
 ```yml
controller:
  componentName: jenkins-controller
  image: "jenkins/jenkins"
  tag: lts-jdk11
  imagePullPolicy: IfNotPresent
  installPlugins: false
  disableRememberMe: false
  serviceType: ClusterIP
  persistence:
    enabled: true
    existingClaim: efs-pvc

  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    ingressClassName: nginx
    kubernetes.io/ingress.class: nginx
    rules:
    - host: foo.jenkins.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jenkins
              port:
                number: 80
    tls:
     - secretName: jenkins-tls
       hosts:
         - foo.jenkins.com
```

5. check that jenkins pod is using the right pvc
```console
kc get sc,pv,pvc -n jenkins
NAME                                        PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
storageclass.storage.k8s.io/efs-sc          efs.csi.aws.com         Delete          Immediate              false                  133m
storageclass.storage.k8s.io/gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   false                  3h11m

NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM             STORAGECLASS   REASON   AGE
persistentvolume/efs-pv                                     5Gi        RWX            Retain           Bound    jenkins/efs-pvc   efs-sc                  133m
persistentvolume/pvc-00793bff-1cd9-4b81-aeea-046d71bdc9b1   8Gi        RWO            Delete           Bound    jenkins/jenkins   gp2                     16m

NAME                            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/efs-pvc   Bound    efs-pv                                     5Gi        RWX            efs-sc         133m
persistentvolumeclaim/jenkins   Bound    pvc-00793bff-1cd9-4b81-aeea-046d71bdc9b1   8Gi        RWO            gp2            16m

```
and confirm that jenkins is not using the specified pvc

6. check the mounted volumes using `mount` and verify that there are no NFS mounted volumes

**Anything else we need to know**:

I tested with a different example from https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/examples/kubernetes/multiple_pods
the EFS volume was successfully mounted and data was written as expected
