### ISSUE TITLE
Configuration changes do not persist between pod restarts

### ISSUE THREAD

**Issue by nwithers-ecr** [jenkinsci/helm-charts#494]
**Describe the bug**
Configuration changes such as updates to configureClouds or ConfigureSecurity/SecurityRealm do not persist when made through the UI when the pod cycles. For example, my ec2-fleet cloud config and Global GitHub OAuth Settings completely reset after installing plugin updates which cause the pod to restart. 

**Version of Helm and Kubernetes**:

Helm Version:

```console
❯ helm version
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

Kubernetes Version:

```console
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8+rke2r1", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-23T23:30:36Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
v3.5.11

**What happened**:
Security realm updates disappeared on pod restart

**What you expected to happen**:
Configuration changes made from the UI persist after pod restart

**How to reproduce it** (as minimally and precisely as possible):

```yaml
---
clusterZone: "us-gov-west-1"

controller:
  tag: "2.303.2-jdk11"

  # List of plugins to be install during Jenkins controller start
  installPlugins:
    - blueocean:1.25.1
    - configuration-as-code:1.52
    - git:4.8.2
    - github:1.34.0
    - kubernetes:1.30.1
    - workflow-aggregator:2.6
    - github-oauth:0.34
    - ec2-fleet:2.3.6
    - matrix-auth:2.6.8
    - Office-365-Connector:4.15.2
    - pipeline-github:2.7
    - ssh-agent:1.23

  # Set to false to download the minimum required version of all dependencies.
  installLatestPlugins: false

  # Set to true to download latest dependencies of any plugin that is requested to have the latest version.
  installLatestSpecifiedPlugins: true

  ingress:
    enabled: true
    hostName: "my_url"
    annotations:
      acme.cert-manager.io/http01-ingress-class: nginx
      cert-manager.io/acme-challenge-type: http01
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - secretName: jenkins-tls-cert
        hosts:
          - "my_url"

agent:
  tag: "4.6-1"

persistence:
  existingClaim: jenkins-pvc
  storageClass: jenkins-pv
```
Jenkins is deployed via fluxcd
