### ISSUE TITLE
New Jenkins instance fails to create /data/jenkins-volume/

### ISSUE THREAD

**Issue by mcr-paulanand** [jenkinsci/helm-charts#515]
**Describe the bug**
New Jenkins instance fails to create `/data/jenkins-volume/` with default UID

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1302", GitCommit:"639f3a74abf258418493e9b75f2f98a08da29733", GitTreeState:"clean", BuildDate:"2021-10-21T21:35:48Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
jenkins-3.9.3

**What happened**:
When initialising the Jenkins container, the following error is thrown in GKE:
```
failed to generate container "7a9391403e07dd99c02ed768f2a7e0cdcd377efc5923932ae259621637d9d997" spec: failed to generate spec: failed to mkdir "/data/jenkins-volume/": mkdir /data: read-only file system: CreateContainerError
```

**What you expected to happen**:
The Jenkins container to start up without errors.

**How to reproduce it** (as minimally and precisely as possible):

1. I am attempting to set up a fresh instance of Jenkins in GKE. I am following the guide by [Jenkins](https://www.jenkins.io/doc/book/installing/kubernetes/#install-jenkins-with-helm-v3).
2. I create a PV:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins
spec:
  storageClassName: jenkins-pv
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-volume/
```
3. I create a SA (I am creating it for the namespace Jenkins rather that the entire cluster):
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: jenkins
  namespace: jenkins
rules:
- apiGroups:
  - '*'
  resources:
  - statefulsets
  - services
  - replicationcontrollers
  - replicasets
  - podtemplates
  - podsecuritypolicies
  - pods
  - pods/log
  - pods/exec
  - podpreset
  - poddisruptionbudget
  - persistentvolumes
  - persistentvolumeclaims
  - jobs
  - endpoints
  - deployments
  - deployments/scale
  - daemonsets
  - cronjobs
  - configmaps
  - namespaces
  - events
  - secrets
  verbs:
  - create
  - get
  - watch
  - delete
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: jenkins
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:jenkins

```
4. Install Jenkins using Helm:
```
helm install jenkins -n jenkins -f jenkins-values.yaml jenkins/jenkins
```
**The difference in jenkins-values.yaml**
```
  disableRememberMe: true

  podSecurityContextOverride:
    runAsUser: 1000
    runAsNonRoot: true
    supplementalGroups: [1000]
    # capabilities: {}

  podDisruptionBudget:
    enabled: true
    apiVersion: "policy/v1"

persistence:
  enabled: true
  existingClaim:
  storageClass: jenkins-pv

serviceAccount:
  create: false
  name: jenkins
```

**Anything else we need to know**:
