### ISSUE TITLE
CASC_JENKINS_CONFIG - support for remote url

### ISSUE THREAD

**Issue by ShankarSumanth** [jenkinsci/helm-charts#530]
**Is your feature request related to a problem? Please describe.**
The JCasC plugin supports three variations of providing the value to this environment variable. 
- Path to a folder containing a set of config files. For example, /var/jenkins_home/casc_configs.
- A full path to a single file. For example, /var/jenkins_home/casc_configs/jenkins.yaml.
- A URL pointing to a file served on the web. For example, https://acme.org/jenkins.yaml.

The third option is not supported by the helm chart. 
This would help to externalize the whole jenkins-casc.yaml from the values.yaml file and store it in git.

**Describe the solution you'd like**
support the URL option via values as an additional option to jenkins casc configuration. 
```
controller:
  JCasC: https://acme.org/jenkins.yaml

// or

controller:
  JCasC: 
    url: https://acme.org/jenkins.yaml

```

**Describe alternatives you've considered**
N/A. 

**Additional context**
