### ISSUE TITLE
Jenkins fails to load any plugin and stops

### ISSUE THREAD

**Issue by DerKnerd** [jenkinsci/helm-charts#545]
**Describe the bug**
After updating my Jenkins install from 2.228 to 2.330 Jenkins fails to start. The log is attached.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.4"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"archive", BuildDate:"2022-01-05T21:51:35Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.8-3+119a51a7fb9a28", GitCommit:"119a51a7fb9a28064897c9b62b6c70fc82253df7", GitTreeState:"clean", BuildDate:"2022-01-07T02:22:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
3.11.1

[jenkins-0.log](https://github.com/jenkinsci/helm-charts/files/7885210/jenkins-0.log)

**Comment by DerKnerd** [comment]
I completely missed the values.yaml check here:

```yaml
controller:
  componentName: "jenkins-controller"
  image: "jenkins/jenkins"
  tag: "2.330"
  imagePullPolicy: "Always"
  imagePullSecretName:

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - configuration-as-code
    - material-theme
    - blueocean
    - gitea

  sidecars:
    configAutoReload:
      enabled: true
      image: kiwigrid/k8s-sidecar:1.15.0
      imagePullPolicy: IfNotPresent

  ingress:
    enabled: true
    paths: []
    apiVersion: "networking.k8s.io/v1"
    labels: {}
    annotations:
      kubernetes.io/ingress.class: public
      kubernetes.io/tls-acme: "true"
      cert-manager.io/issuer: "dev-imanuel-jenkins-letsencrypt-prod"
    hostName: jenkins.imanuel.dev
    tls:
      - secretName: dev-imanuel-jenkins-letsencrypt-prod
        hosts:
          - jenkins.imanuel.dev
  JCasC:
    authorizationStrategy: |-
      projectMatrix:
        permissions:
        - "Job/Read:anonymous"
        - "Overall/Read:anonymous"
persistence:
  enabled: true
  existingClaim:
  storageClass:
  annotations: {}
  accessMode: "ReadWriteOnce"
  size: "1000Gi"
  volumes:
  mounts:

agent:
  enabled: true
  defaultsProviderTemplate: "default"
  jenkinsUrl:
  jenkinsTunnel:
  kubernetesConnectTimeout: 5
  kubernetesReadTimeout: 15
  maxRequestsPerHostStr: "32"
  namespace:
  image: quay.imanuel.dev/dockerhub/jenkins---inbound-agent
  tag: "latest"
  workingDir: "/home/jenkins/agent"
  nodeUsageMode: "NORMAL"
  customJenkinsLabels: []
  imagePullSecretName:
  componentName: "jenkins-agent"
  websocket: false
  privileged: false
  runAsUser:
  runAsGroup:
  resources:
    requests:
      cpu: "512m"
      memory: "512Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"
  alwaysPullImage: true
  podRetention: "Never"
  showRawYaml: true
  volumes: []
  workspaceVolume: {}
  envVars: []
  nodeSelector: {}
  command:
  args: "${computer.jnlpmac} ${computer.name}"
  sideContainerName: "jnlp"
  TTYEnabled: false
  containerCap: 10
  podName: "default"
  idleMinutes: 0
  yamlTemplate: ""
  yamlMergeStrategy: "override"
  connectTimeout: 100
  annotations: {} is https://<jenkins_url>/configuration-as-code/reference#Cloud-kubernetes. The example below creates a python pod template.
  podTemplates: {}
```
