### ISSUE TITLE
podTemplates are not loaded

### ISSUE THREAD

**Issue by erez-dome9** [jenkinsci/helm-charts#55]
Lately it appears that my podTemplate configuration (under the `agent` section) is not loaded and only the default template is created.

**Version of Helm and Kubernetes**:

```console
$ helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Kubernetes Version: 

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T23:41:24Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**: Latest

**What happened**: podTemplate configuration isn't loaded

The values (only the agent part):
```
agent:
  enabled: true
  image: jenkins/jnlp-slave
  tag: 3.27-1
  customJenkinsLabels: []
  imagePullSecretName:
  componentName: jenkins-slave
  privileged: false
  resources:
    requests:
      cpu: 512m
      memory: 512Mi
    limits:
      cpu: 512m
      memory: 512Mi
  alwaysPullImage: false
  podRetention: Never
  volumes: []
  envVars: []
  nodeSelector: {}
  command:
  args: ${computer.jnlpmac} ${computer.name}
  sideContainerName: jnlp
  TTYEnabled: false
  containerCap: 10
  podName: default
  idleMinutes: 0
  slaveConnectTimeout: 100
  podTemplates:
    python: |
      - name: python-agent
        label: python
        serviceAccount: build-jenkins-agent
        containers:
          - name: python
            image: 184642232056.dkr.ecr.us-east-1.amazonaws.com/devops/jenkins/slave/python37:latest
            command: "sleep"
            args: "infinity"
    node: |
      - name: node-agent
        label: node
        serviceAccount: access-to-automation-account
        containers:
          - name: node
            image: node:10.16.3
            command: "sleep"
            args: "infinity"
```
