### ISSUE TITLE
Locale configuration

### ISSUE THREAD

**Issue by vittoriocanilli** [jenkinsci/helm-charts#556]
### Is your feature request related to a problem? Please describe

I have setup Jenkins on my Kubernetes cluster to replace my current Jenkins server running on an Azure virtual machine, where the locale is set to English via the [Locale plugin](https://plugins.jenkins.io/locale/); with this Helm chart, the new Jenkins setup uses the user browser's locale (default configuration).

I have then installed the Locale plugin with the proper values:
```
  additionalPlugins:
    - locale:1.4
```

Unfortunately there is no way to configure the plugin on this Helm chart. I know that I can manually insert the desired settings on the Jenkins GUI, but I am looking for an automated configuration.

### Describe the solution you'd like

I would like to set the desired Jenkins locale as value of the Helm chart.

### Describe alternatives you've considered

At first I wanted to configure the Locale plugin via JCasc, but the Locale plugin does not support JCasc at the moment; more information can be found in this [Jenkins issue](https://issues.jenkins.io/browse/JENKINS-52205) and in this [GitHub PR](https://github.com/jenkinsci/locale-plugin/pull/5).

### Additional context

I suppose that I am not the first one with this problem, so I am open to alternative working solutions, in case the proposed one is not feasible.

**Comment by vittoriocanilli** [comment]
This feature is no more necessary, as the previously mentioned [Jenkins issue](https://issues.jenkins.io/browse/JENKINS-52205) has been resolved some days ago with a different [GitHub PR](https://github.com/jenkinsci/locale-plugin/pull/12) of the [Locale plugin](https://plugins.jenkins.io/locale/).

I have managed to solve my previously described problem by installing a version of the Locale plugin, which is newer than **1.4**. More details can be found below:

```
controller:

  additionalPlugins:
    - locale:144.v1a_998824ddb_3

  JCasC:
    configScripts:
      locale: |
        unclassified:
          locale:
            systemLocale: en_US
            ignoreAcceptLanguage: true
```

Therefore I can close now this issue.
