### ISSUE TITLE
Some Jenkins plugins could not be update

### ISSUE THREAD

**Issue by vittoriocanilli** [jenkinsci/helm-charts#557]
### Describe the bug

I have setup my new Jenkins environment with the following Helm values file:

```
controller:
  installPlugins:
    - kubernetes:1.31.3
    - workflow-aggregator:2.6
    - git:4.10.3
    - configuration-as-code:1346.ve8cfa_3473c94

  additionalPlugins:
    - ansible:1.1
    - ansicolor:1.0.1
    - artifactory:3.15.3
    - authorize-project:1.4.0
    - azure-ad:191.vfc8019068670
    - azure-cli:0.9
    - basic-branch-build-strategies:1.3.2
    - blueocean:1.25.2
    - blueocean-jira:1.25.2
    - build-monitor-plugin:1.13+build.202201311821
    - build-user-vars-plugin:1.8
    - build-with-parameters:1.6
    - chromedriver:1.2
    - embeddable-build-status:2.0.3
    - extended-choice-parameter:0.82
    - extended-read-permission:3.2
    - external-monitor-job:191.v363d0d1efdf8
    - gatling:1.3.0
    - git-parameter:0.9.15
    - github-pullrequest:0.4.0
    - google-oauth-plugin:1.0.6
    - http_request:1.14
    - jacoco:3.3.1
    - locale:1.4
    - liquibase-runner:1.4.10
    - m2release:0.16.2
    - netsparker-cloud-scan:2.1.4
    - pam-auth:1.7
    - parameter-separator:1.3
    - parameterized-scheduler:1.0
    - parameterized-trigger:2.43
    - pipeline-utility-steps:2.12.0
    - pipeline-github-lib:36.v4c01db_ca_ed16	
    - pipeline-multibranch-defaults:2.1
    - saml:2.1.1-275.va_5718591a_999
    - slack:602.v0da_f7458945d
    - sonar:2.14
    - ssh-agent:1.24.1
    - ssh-slaves:1.33.0
    - thinBackup:1.10
    - timestamper:1.17
    - violation-comments-to-github:1.95
    - warnings-ng:9.11.0
    - windows-azure-storage:365.vf41653c43b01
    - ws-cleanup:0.40

  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    ingressClassName: nginx
    hostName:
      jenkins.devops.azure.example.com
    tls:
    - secretName: le-jenkins-devops-tls
      hosts:
        - jenkins.devops.azure.example.com

persistence:
  existingClaim: jenkins-devops-volume

```

Besides the requested Jenkins plugins, some other ones were installed as dependencies; three of them were installed with a version, which is not the latest one:

- [JAXB](https://plugins.jenkins.io/jaxb/) installed 2.3.0 while the latest one is 2.3.0.1
- [Oracle Java SE Development Kit Installer](https://plugins.jenkins.io/jdk-tool/) installed 1.0 while the latest one is 1.5
- [WMI Windows Agents](https://plugins.jenkins.io/windows-slaves/) installed 1.0 while the latest one is 1.8

Therefore I have decided to add these 3 plugins with their latest versions explicitly to the Helm values:

```
...
  additionalPlugins:
    - ...
    - jaxb:2.3.0.1
    - jdk-tool:1.5
    - windows-slaves:1.8
    - ...
...
```

Unfortunately this did not help to update the 3 plugins. Moving all plugins to the `installPlugins` value did not help either.

### Version of Helm and Kubernetes

```markdown
- Helm: v3.7.2
- Kubernetes: v1.22.4 (client), v1.21.2 (server)
```

### Chart version

jenkins-3.11.3

### What happened?

```bash
1. Install the Helm chart (value files above and command below)
  1a. the complete value files requires that a certificate and a pvc are created in the same 
      Kubernetes namespace in advance (manifest files available below)
2. Verify whether all plugins are installed to their latest version
3. Add the not-updated plugins explicitly to the value files and upgrade the Helm chart
4. Verify again whether all plugins are installed to their latest version this time
5. Move all plugins to "installPlugins" in the value files and upgrade the Helm chart again
6. Verify once again whether all plugins are installed to their latest version now
```

### What you expected to happen?

All plugins should have been updated.

### How to reproduce it

```markdown
helm install jenkins jenkins/jenkins \
  --namespace example-devops \
  --values helm/values.yaml \
  --set controller.tag="2.319.2-jdk11" \
  --version 3.11.3

(the values.yaml file can be found in the bug description above)
```

### Anything else we need to know?

Here are the YAML manifest files of the certificate and the pvc, if necessary:

```
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-jenkins-devops-tls
  namespace: example-devops
spec:
  secretName: le-jenkins-devops-tls
  dnsNames:
  - jenkins.devops.azure.example.com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
```

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-devops-volume
  namespace: example-devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: westeurope-1
```

This has been executed on an AKS (Azure) Kubernetes cluster.
