### ISSUE TITLE
Improvement to documentation

### ISSUE THREAD

**Issue by ErikEngerd** [jenkinsci/helm-charts#562]
Hi, 

I was experimenting today with setting up Jenkins on a GKE autopilot cluster and had a lot of problems getting it to work. The deploy would take a very long time and ended up in a 'CrashLoopBackoff'.

The issue turned out to be due to the resource configuration for CPU:
``` 
 resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
```

On an autopilot cluster, it appears that you get exactly the amount of CPU you reserve, but not more. Therefore, with only 0.05 CPU to startup, startup would take a long time and finally it would fail. 

I think either the default should be changed to a higher value  (e.g. 500m) or there should be some extra comments in the values file indicating that on some setups you must choose a higher value.
