### ISSUE TITLE
script.sh: 2: docker: not found

### ISSUE THREAD

**Issue by uralsemih** [jenkinsci/helm-charts#564]
### Describe the bug

I deployed Jenkins on Kubernetes and it is up and running without any issue. But when I would like to run docker command in the pipeline I am getting and` docker:not found` error. What should I change in the helm chart to be able to run docker commands?

```
node {
  stage('SCM') {
    checkout(scm)
  }
  stage('Build') {
    echo 'Building Project'
    sh """
      docker pull alpine
    """
  }

----
+ docker pull alpine
/home/jenkins/agent/workspace/experiments-pipeline@tmp/durable-4c43b96b/script.sh: 2: docker: not found
```

Here is values.yaml
agent:
  enabled: true
  volumes:
  - type: HostPath
    hostPath: /Users/username/workspace
    mountPath: /Users/username/workspace
  - type: HostPath
    hostPath: /var/run/docker.sock
    mountPath: /var/run/docker.sock
persistence:
  enabled: true
  storageClass:
  annotations: {}
  labels: {}
  accessMode: "ReadWriteOnce"
  size: "8Gi"
  volumes:
    - name: source-code
      hostPath:
        path: /Users/username/workspace
  mounts:
    - mountPath: /Users/username/workspace
      name: source-code

### Version of Helm and Kubernetes

```markdown
- Helm: v3.8.0
- Kubernetes: v1.23
```

### Chart version

jenkins -3.11.4

### What you expected to happen?

able to run docker command in the pipeline

**Comment by torstenwalter** [comment]
docker is not included in the default build pod (agent image).

**Comment by uralsemih** [comment]
so do I have to use custom image or is there easier way to do achieve this ?

**Comment by uralsemih** [comment]
@torstenwalter thanks for the detailed information but this is a bit complex for the local enviroment.

Actually, I was able to install docker via a custom image as below but this time I am getting a permission error where I am stuck. Added Jenkins user to docker group did not fix permission issue. In the values.yaml. `I tried to add command: ["sh", "-c", "chown -R jenkins:docker /var/run/docker.sock"]` but this time pod CrashLoopBackOff wit below error

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/var/jenkins_cache/war/WEB-INF/lib/guice-4.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2022-02-11 11:59:28.658+0000 [id=29]	INFO	jenkins.InitReactorRunner$1#onAttained: Prepared all plugins
2022-02-11 11:59:28.951+0000 [id=31]	INFO	jenkins.InitReactorRunner$1#onAttained: Started all plugins
2022-02-11 11:59:29.152+0000 [id=31]	INFO	jenkins.InitReactorRunner$1#onAttained: Augmented all extensions
2022-02-11 11:59:36.001+0000 [id=32]	INFO	jenkins.InitReactorRunner$1#onAttained: System config loaded
2022-02-11 11:59:38.100+0000 [id=32]	WARNING	i.j.p.casc.BaseConfigurator#createAttribute: Can't handle class org.csanchez.jenkins.plugins.kubernetes.PodTemplate#listener: type is abstract but not Describable.
2022-02-11 11:59:38.229+0000 [id=32]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed ConfigurationAsCode.init
io.jenkins.plugins.casc.ConfiguratorException: Item isn't a Scalar
	at io.jenkins.plugins.casc.model.CNode.asScalar(CNode.java:26)
	at io.jenkins.plugins.casc.impl.configurators.PrimitiveConfigurator.configure(PrimitiveConfigurator.java:44)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:351)
```



agent:
  enabled: true
  image: "jenkinsinbound-agent"
  tag: "4.11.2-5"
  workingDir: "/home/jenkins/agent"
  imagePullSecretName:
  componentName: "jenkins-agent"
  websocket: false
  privileged: false
  runAsUser: 
  runAsGroup:
  volumes:
  - type: HostPath
    hostPath: /Users/uralsem/workspace
    mountPath: /Users/uralsem/workspace
  - type: HostPath
    hostPath: /var/run/docker.sock
    mountPath: /var/run/docker.sock
   command: ["sh", "-c", "chown -R jenkins:docker /var/run/docker.sock"]


```
FROM jenkins/inbound-agent:4.11.2-4
USER root
RUN set -eux && \
    apt-get update && \
    apt-get install -y docker.io docker-compose && \
    curl -sS https://raw.githubusercontent.com/HariSekhon/bash-tools/master/clean_caches.sh | sh
RUN usermod -g docker jenkins
RUN usermod -a -G jenkins jenkins
USER jenkins
```

```
+ docker pull alpine
Using default tag: latest
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=alpine&tag=latest": dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by torstenwalter** [comment]
Your `chown` commands exits immediately. No matter if it's failing or succesful once the process is finished the container will be restarted by Kubernetes.

**Comment by uralsemih** [comment]
so what is the best way of granting permission through the chart for` /var/run/docker.sock`

**Comment by torstenwalter** [comment]
I never tried as it's from a security point of view a bad idea.

**Comment by aushafy** [comment]
I have run Jenkins in K8s for more than 6 months, I have another suggest for you to use different approach for Building Docker Image inside of Kubernetes, you can use Docker-in-Docker or Kaniko for more secure rather than Install Docker inside of inbound-agent. feel free to contact me if you want more details

**Comment by gwasky** [comment]
https://blog.thecloudside.com/docker-in-docker-with-jenkins-pod-on-kubernetes-f2b9877936f2

**Comment by martmalo** [comment]
> I have run Jenkins in K8s for more than 6 months, I have another suggest for you to use different approach for Building Docker Image inside of Kubernetes, you can use Docker-in-Docker or Kaniko for more secure rather than Install Docker inside of inbound-agent. feel free to contact me if you want more details

@aushafy can you contact me about this issue on martmalo@proton.me?

**Comment by SheplX** [comment]
> so what is the best way of granting permission through the chart for` /var/run/docker.sock`

hi, try this:

FROM jenkins/inbound-agent
USER root
RUN set -eux && \
    apt-get update && \
    apt-get install -y docker.io docker-compose && \
    curl -sS https://raw.githubusercontent.com/HariSekhon/bash-tools/master/clean_caches.sh | sh
ENV USER jenkins
RUN usermod -aG docker ${USER}
RUN newgrp docker

**Comment by stevelaclasse** [comment]
Here are the settings that i have used to make it work. I have unfortunately used the **root** user for the agent .

**Jenkins agent custom Dockerfile:**

```
FROM jenkins/inbound-agent:3107.v665000b_51092-15
USER root
RUN apt update && apt install apt-transport-https ca-certificates curl gnupg lsb-release -y
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
RUN apt-get update && apt -y install docker-ce docker-ce-cli containerd.io 

RUN usermod -aG docker jenkins

USER jenkins 
```


**Jenkins agent helm values custom file:**

```
agent:
  image: "#custom-registry-with-new-jenkins-agent/jenkins-agent"
  tag: "latest"
  #set the user to root to access the share workspace on the host, as Jenkins create the PVC with root access
  #didn't work with Userid 1000
  runAsUser: 0
  fsGroup: 0
  volumes:
  - type: HostPath
    hostPath: /tmp/jenkins_workspace
    mountPath: /tmp/jenkins_workspace
  - type: HostPath
    hostPath: /var/run/docker.sock
    mountPath: /var/run/docker.sock
  resources:
    requests:
      cpu: "512m"
      memory: "2048Mi"
    limits:
      cpu: "512m"
      memory: "2048Mi"
  workingDir: /tmp/jenkins_workspace
```

**Comment by m0dularm1nd** [comment]
> Here are the settings that i have used to make it work. I have unfortunately used the **root** user for the agent .
> 
> **Jenkins agent custom Dockerfile:**
> 
> ```
> FROM jenkins/inbound-agent:3107.v665000b_51092-15
> USER root
> RUN apt update && apt install apt-transport-https ca-certificates curl gnupg lsb-release -y
> RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
> RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
>     $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
> RUN apt-get update && apt -y install docker-ce docker-ce-cli containerd.io 
> 
> RUN usermod -aG docker jenkins
> 
> USER jenkins 
> ```
> 
> **Jenkins agent helm values custom file:**
> 
> ```
> agent:
>   image: "#custom-registry-with-new-jenkins-agent/jenkins-agent"
>   tag: "latest"
>   #set the user to root to access the share workspace on the host, as Jenkins create the PVC with root access
>   #didn't work with Userid 1000
>   runAsUser: 0
>   fsGroup: 0
>   volumes:
>   - type: HostPath
>     hostPath: /tmp/jenkins_workspace
>     mountPath: /tmp/jenkins_workspace
>   - type: HostPath
>     hostPath: /var/run/docker.sock
>     mountPath: /var/run/docker.sock
>   resources:
>     requests:
>       cpu: "512m"
>       memory: "2048Mi"
>     limits:
>       cpu: "512m"
>       memory: "2048Mi"
>   workingDir: /tmp/jenkins_workspace
> ```

heyy,

i tried using same values and image and still getting permission issues, any idea what to look for

> ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied

**Comment by leszko** [comment]
You may try the following `value.yaml`. It worked for me.

```
agent:
  disableDefaultAgent: true
  additionalContainers:
    - sideContainerName: dind
      image:
        repository: docker
        tag: dind
      command: dockerd-entrypoint.sh
      args: ""
      privileged: true
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
additionalAgents:
  docker:
    podName: docker
    customJenkinsLabels: docker
    envVars:
      - name: DOCKER_HOST
        value: "127.0.0.1"
      - name: DOCKER_TLS_CERTDIR
        value: ""
    image:
      repository: jenkins/jnlp-agent-docker
      tag: latest
```
