### ISSUE TITLE
Support envFrom.configMapRef to the jenkins sts?

### ISSUE THREAD

**Issue by dev-samples** [jenkinsci/helm-charts#580]
### Is your feature request related to a problem? Please describe

Maybe this is already possible and I have missed it but I would like to be able to specify the name of a configmap that should be used to set envs like **special-config** below:

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#configure-all-key-value-pairs-in-a-configmap-as-container-environment-variables

```
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: special-config
  restartPolicy: Never
```

Right now  I can add each var like:

```
  values:
    controller:
      containerEnv:
        - name: VAR_A
          value: "valuea"
        - name: VAR_B
          value: "valueb"

```

But I would like to store a set of specific env vars in a separate configmap an then reference that in the statefulset.
