### ISSUE TITLE
DirectoryOrCreate for HostPath volumes?

### ISSUE THREAD

**Issue by dev-samples** [jenkinsci/helm-charts#581]
### Is your feature request related to a problem? Please describe

In the values file its possible to create a volume of type HostPath:
https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml#L628

```
  volumes: []
  # - type: HostPath
  #   hostPath: /var/lib/containers
  #   mountPath: /var/myapp/myhostpath
```
but I need **DirectoryOrCreate** in case the dir does not exist on the worker node (e.g. when the node autoscaler kicks in).

I do this in another project:

```
  - name: test-volume-1
    hostPath:
      path: /var/tmp/gradle-cache/gradle
      type: DirectoryOrCreate

```

Any suggestions to enable this option?
