### ISSUE TITLE
controller: admin: existingSecret does not work

### ISSUE THREAD

**Issue by LevonBecker** [jenkinsci/helm-charts#584]
### Describe the bug

```yaml
  admin:
    existingSecret: ""
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password
```
This example is from the default values output (helm show values jenkins/jenkins). It doesn't seem to do anything. With or without adminSecret: true/false

### Version of Helm and Kubernetes

```markdown
- Helm: 3.8.0
- Kubernetes: 1.22.5
```

### Chart version

jenkins-3.11.6

### What happened?

```bash
Set values but the helm template is not setting them at all in StatefulSet
```

### What you expected to happen?

Set Helm Chart Values from the defaults output (helm show values jenkins/jenkins). Helm template adds to jenkins StatefulSet. Add existing secret with user and password key names to then set the adminUser and adminPassword

### How to reproduce it

# Secret

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jenkins-auth
  namespace: jenkins
data:
  # user = admin
  admin-user: YWRtaW4=
  # password = jenkins
  admin-password: amVua2lucw==
```

# Chart values.yaml
```yaml
controller:
  adminSecret: false
  admin:
    existingSecret: jenkins-auth
    userKey: admin-user
    passwordKey: admin-password
```
OR

```yaml
controller:
  adminSecret: true
  admin:
    existingSecret: jenkins-auth
    userKey: admin-user
    passwordKey: admin-password
```
```


### Anything else we need to know?

No error with adminSecret: true, because it makes a generated secret and plugs in values correctly. Although, it is not our set user and password from our secret. It's the generated ones.

**Comment by LevonBecker** [comment]
I had something wrong. Think testing with adminSecret: false and then janked up the code when testing with that set to true. Seems to be working as expected.

Need to have adminSecret: true. This doesn't only mean create admin secret etc.

This works!
```yaml
controller:
  adminSecret: true
  admin:
    existingSecret: jenkins-auth
    userKey: admin-user
    passwordKey: admin-password
```
