### ISSUE TITLE
additionalAgents - Not overriding serviceAccount value

### ISSUE THREAD

**Issue by psimms-r7** [jenkinsci/helm-charts#603]
### Describe the bug

When passing in additionalAgents and passing in serviceAccount with a different value to the default agents service account, the additional agents template is still picking up the default agents service account as created by serviceAccountAgent.  From what I understand this should override the default agents value

Example template
```
additionalAgents:
  python:
    podName: python
    customJenkinsLabels: python
    sideContainerName: python
    image: python
    tag: "3"
    command: "/bin/sh -c"
    args: "cat"
    TTYEnabled: true
    serviceAccount: "default"
```

### Version of Helm and Kubernetes

```markdown
- Helm: 
- Kubernetes: 1.21
```

### Chart version

3.11.6

### What happened?

```bash
Pass in an additionalAgent with a serviceAccount value different from the default agents value
```

### What you expected to happen?

The value passed in under additionalAgents should override the default agents service account for that template

### How to reproduce it

```markdown
Use the below code for additionalAgents, when deployed check the pod templates for the clouds, check the python pod template and confirm the value under Service Account


additionalAgents:
  python:
    podName: python
    customJenkinsLabels: python
    sideContainerName: python
    image: python
    tag: "3"
    command: "/bin/sh -c"
    args: "cat"
    TTYEnabled: true
    serviceAccount: "default"
```
```


### Anything else we need to know?

_No response_
