### ISSUE TITLE
When specifying agents via PodTemplates, there is no way to disable the default Jenkins agent config

### ISSUE THREAD

**Issue by nabz09** [jenkinsci/helm-charts#608]
### Is your feature request related to a problem? Please describe

I wish to specify my Jenkins agent config through podTemplates alone, my podTemplates are seen below. Although I specify 2 podTemplates, I end up with 3 agent configs. This is because the default agent podTemplate is always configured and there is no way to disable it.

```yaml
agent:
  enabled: true
  podTemplates: 
    agent-name1: |
      - containers:
        - args: "^${computer.jnlpmac} ^${computer.name}"
          command: ""
          envVars:
          - envVar:
              key: "JENKINS_URL"
              value: "http://jenkins.mynamespace.svc.cluster.local:8080/"
          image: "myJenkinsAgentImage:latest"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jnlp"
          ports:
          - containerPort: 8080
            hostPort: 8080
            name: "http"
          resourceLimitCpu: "512m"
          resourceLimitMemory: "512Mi"
          resourceRequestCpu: "512m"
          resourceRequestMemory: "512Mi"
          workingDir: "/home/jenkins/agent"
        id: "a59a0c23b02f5d63dgdgfdgfdgfgd52039a9052f62a8bdbc1ac958da5f"
        idleMinutes: 10
        idleMinutesStr: "10"
        name: "agent-name1"
        namespace: "mynamespace"
        nodeUsageMode: "NORMAL"
        podRetention: "never"
        serviceAccount: "jenkins-agent-service-account"
        slaveConnectTimeout: 100
        slaveConnectTimeoutStr: "100"
        yamlMergeStrategy: "override"
    agent-name2: |
      - containers:
        - args: "^${computer.jnlpmac} ^${computer.name}"
          command: ""
          envVars:
          - envVar:
              key: "JENKINS_URL"
              value: "http://jenkins.mynamespace.svc.cluster.local:8080/"
          image: "myJenkinsAgentImage:latest"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jnlp"
          ports:
          - containerPort: 8080
            hostPort: 8080
            name: "http"
          resourceLimitCpu: "512m"
          resourceLimitMemory: "512Mi"
          resourceRequestCpu: "512m"
          resourceRequestMemory: "512Mi"
          workingDir: "/home/jenkins/agent"
        id: "a59a0c23b0asdfhfghfghgfa8bdbc1ac958da5f"
        idleMinutes: 10
        idleMinutesStr: "10"
        name: "agent-name2"
        namespace: "mynamespace"
        nodeUsageMode: "NORMAL"
        podRetention: "never"
        serviceAccount: "jenkins-agent-service-account"
        slaveConnectTimeout: 100
        slaveConnectTimeoutStr: "100"
        yamlMergeStrategy: "override"
```

### Describe the solution you'd like

I wish to have a values.yml property which can disable the default pod configuration, so that if I only wish to configure agents with podTemplates then I don't have an extra default config lying around.

### Describe alternatives you've considered

I have tried to not use podTemplates for my agent config and instead using the agent value.ymls but the configurable agent properties in value.yml is not a comprehensive list and there is no way to configure a port map from 8080 in the container to 8080 on the host, also I cannot configure volume mounts through agent config.
podTemplates provide maximum flexibility for what I can configure an agent as.
