### ISSUE TITLE
Config Map too long

### ISSUE THREAD

**Issue by dhruv-dave** [jenkinsci/helm-charts#613]
### Describe the bug

The way we have our Jenkins setup, we define all the jobs in the values.yaml file and when jenkins starts up, the jobs are loaded. 

Now I think we have hit a limit with the seeded jobs because when i deploy jenkins, i get this error: `ConfigMap "jenkins-dev" is invalid: []: Too long: must have at most 1048576 bytes`

Here is an example of the `jobs:` key of the `jenkins-dev` config map:
```
 - script: >
         pipelineJob('job-1') {disabled()
             parameters {gitParameter {
                          name('BRANCH')
                          type('Branch')
                          defaultValue('master')
                          description('Branch for Configuration')
                          branch('')
                          branchFilter('origin/(.*)')
                          tagFilter('*')
                          sortMode('ASCENDING_SMART')
                          selectedValue('DEFAULT')
                          useRepository('<git-repo-url>')
                          quickFilterEnabled(true)
                          listSize('5')
                      }
                  choiceParam('OPTIONS', ['python2','python3','both'], 'Unit test options')  
               }
             properties {authorizationMatrix {inheritanceStrategy {
                           inheritingGlobal()
                         }
                         permissions(['USER:Job/Build:user-name1','USER:Job/Build:user-name2']) 
                     }   
               }
             definition {
                 cpsScm {
                     scriptPath 'Jenkinsfile'
                     scm {
                       git {
                       remote { url ('<git-repo-url>')
                                credentials('default')
                        }
                        branch 'master'
                        extensions {}
                       }
                     }
                 }
             }
         }

- script: >
 <another one similar to above for different jenkins pipeline>
```
We have so many, that kubernetes is complaining our config-map is too big (long).

### Version of Helm and Kubernetes

```markdown
- Helm: 
version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}

- Kubernetes: 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Chart version

3.11.10

### What happened?

```bash
We have a list of seed jobs defined in one of values.yaml file. It seems that we have hit a limit of the number of jobs we can possibly have. 

Here is a snippet of what I see when I `helm install` the chart:


Error: release jenkins failed, and has been uninstalled due to atomic being set: ConfigMap "jenkins-dev" is invalid: []: Too long: must have at most 1048576 bytes
helm.go:84: [debug] ConfigMap "jenkins-dev" is invalid: []: Too long: must have at most 1048576 bytes
release jenkins failed, and has been uninstalled due to atomic being set
```
```


### What you expected to happen?

I expected to have an "unlimited" number of jobs i could define without running into Config-Map too long issue.

### How to reproduce it

_No response_

### Anything else we need to know?
Contents of my /var/jenkins_home/casc_configs dir:
```
-rw-r--r--  1 jenkins jenkins    229 Apr 18 16:35 buildDiscarders.yaml
-rw-r--r--  1 jenkins jenkins    570 Apr 18 16:35 gitlab-configs.yaml
-rw-r--r--  1 jenkins jenkins   5691 Apr 18 16:35 jcasc-default-config.yaml
-rw-r--r--  1 jenkins jenkins    453 Apr 18 16:35 jira-configs.yaml
-rw-r--r--  1 jenkins jenkins 757679 Apr 18 16:35 jobs.yaml
-rw-r--r--  1 jenkins jenkins    692 Apr 18 16:35 ldap-settings.yaml
-rw-r--r--  1 jenkins jenkins    386 Apr 18 16:35 mail-settings.yaml
-rw-r--r--  1 jenkins jenkins    652 Apr 18 16:35 matrix-auth.yaml
-rw-r--r--  1 jenkins jenkins   2880 Apr 18 16:35 nodes.yaml
-rw-r--r--  1 jenkins jenkins    793 Apr 18 16:35 shared-libs.yaml
-rw-r--r--  1 jenkins jenkins     94 Apr 18 16:35 tool.yaml
-rw-r--r--  1 jenkins jenkins    104 Apr 18 16:35 welcome-message.yaml
```

**Comment by dhruv-dave** [comment]
I mislabeled this as a bug. 
For all the pipelines I had configured, i was generating the script block and putting it in the config map, with 200 pipelines, the config map was getting too large.

I now follow the github/gitlab organizations method. 
[Example Github Organization Project](https://docs.cloudbees.com/docs/cloudbees-jenkins-platform/latest/github-branch-source#github-branch-source-sect-project)

**Comment by dhruv-dave** [comment]
Mislabeled as a `bug`

**Comment by patsevanton** [comment]
@dhruv-dave Could you help to add simple jobs to helm-chart ? May mini guide.

**Comment by dhruv-dave** [comment]
Sorry, I didn't understand.
Do you need help to add jobs to Jenkins through this helm chart?

**Comment by patsevanton** [comment]
@dhruv-dave I think i founded. collecting information about jobs in JCasC for helm chart bit by bit. Thanks for answer. Do you have more examples?

my helm value
```
---
controller:
  tag: "2.346.2-jdk11"
  imagePullPolicy: "IfNotPresent"
  numExecutors: 1

  additionalPlugins:
    - google-login:1.6
    - job-dsl:1.81
    - allure-jenkins-plugin:2.30.2

  JCasC:
    configScripts:
      jenkins-configuration: |
        jenkins:
          systemMessage: This Jenkins is configured and managed 'as code' by Managed Cloud team.
      freestyle-jobs: |
        jobs:
          - script: >
              job('ff') {
                steps {
                  shell('echo $ENV;ls -l')
                }
              }
          - script: >
              job('gg') {
                steps {
                  shell('echo $PWD;ls -l')
                }
              }
    securityRealm: |-
      googleOAuth2:
        clientId: "xx-xxx.apps.googleusercontent.com"
        clientSecret: "xxx-xxx"
        domain: ""
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false

  ingress:
    enabled: true
    ingressClassName: nginx
    apiVersion: networking.k8s.io/v1
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hostName: xxx
    tls:
     - secretName: jenkins-tls
       hosts:
         - xxx
```
