### ISSUE TITLE
Missing global environment variables in Jenkins and must be inherited to each Jenkins slave

### ISSUE THREAD

**Issue by sourabhsharma-devsecops-specialist** [jenkinsci/helm-charts#624]
### Describe the bug

Using this Helm chart, I've been trying to enable/set the Global environment variables in Jenkins (as attached) such as proxy details etc.. 

By setting up the environment variables under Global properties in Jenkins configuration section, this helps to get those environments values for all the Jenkins slave automatically.

<img width="688" alt="Screen Shot 2022-05-16 at 8 37 00 PM" src="https://user-images.githubusercontent.com/104004795/168625335-08b25e23-d86c-4f2a-86d2-b454b7e6f545.png">

### Version of Helm and Kubernetes

```markdown
- Helm: v3.8.2
- Kubernetes: v1.23.6
```

### Chart version

jenkins-2.329

### What you expected to happen?

Set the environment variables globally which must be inherited to each Jenkins slave such as proxy details etc...

**Comment by sourabhsharma-devsecops-specialist** [comment]
@timja - I am using this helm chart and want to enable the environment variable globally by the code and not from the UI. So can you suggest, how this is possible using this helm chart.

**Comment by timja** [comment]
Use the configuration as code plugin

You can configure it and then export the configuration using the export functionality:
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/configExport.md

and then add it to the configuration as code support in the helm chart:
https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins#configuration-as-code

**Comment by jimsnab** [comment]
@timja comment above is excellent and helped me understand the way of converting manual configuration to helm chart `values.yaml`.

Just so others know they are on track, my working global variable config looks like this in my `values.yaml`:

```
controller:
  JCasC:
    # The inner name like 'global-vars' is your choice, but it ends up in a configmap
    # key and must be alphanumeric with optional middle dashes and dots.

    configScripts:
      global-vars: |
        jenkins:
          globalNodeProperties:
          - envVars:
              env:
              - key: "PROJECT_NAME"
                value: "${project_name}"
              - key: "ARTEFACT_SERVER"
                value: "${harbor_dns_name_full}"
              - key: "DEPLOYMENT_SERVER"
                value: "${argocd_dns_name_full}"
```
