### ISSUE TITLE
Need to inform the default region of S3 buckets for backup is set to `eu-central-1`

### ISSUE THREAD

**Issue by uniglot** [jenkinsci/helm-charts#631]
### Is your feature request related to a problem? Please describe

I wanted to enable backup backed by an S3 bucket located in the region `ap-northeast-2`. But I ran into a weird problem complaining like "`BucketRegionError: incorrect region, the bucket is not in 'eu-central-1' region at endpoint ''`"

<img width="998" alt="스크린샷 2022-05-24 15 35 22" src="https://user-images.githubusercontent.com/18096835/170004954-82672beb-d610-4df2-8c4f-b98d7c975162.png">

Naturally, I tried to look for any clues from this repository at first, but I couldn't find out any explicit mentions which are related to this behavior.

### Describe the solution you'd like

As I needed to enable backup no matter what, I dug into the problem. Then I figured out that this error is from 'maorfr/skbn', where it set the default region for S3 buckets to be `eu-central-1`. If someone wants to use an S3 bucket that is outside of that region, they need to declare an environmental variable `AWS_REGION` explicitly ([Please refer to the original code](https://github.com/maorfr/skbn/blob/master/pkg/skbn/s3.go#L163-L192)).

So I added `env` under the `backup` values as below:

```
        backup:
          enabled: true
          schedule: "0 18 * * *"
          existingSecret:
            <SECRETNAME>:
              awsaccesskey: AWS_ACCESS_KEY_ID
              awssecretkey: AWS_SECRET_ACCESS_KEY
          destination: "s3://BUCKETNAME/PATH"
          env:
            - name: AWS_REGION
              value: ap-northeast-2
```

and it worked.

I believe that it would be beneficial to mention the default value for the region for those who want to use the backup feature using the AWS backend.
