### ISSUE TITLE
Duplicated kubernetes configuration using JCasC

### ISSUE THREAD

**Issue by galindro** [jenkinsci/helm-charts#64]
**Describe the bug**
After a fresh deploy of this helm chart using JCasC to configure kubernetes plugin, somehow cloud configuration is configured with two kubernetes entries:

![image](https://user-images.githubusercontent.com/4622097/93588723-19288b00-f9ac-11ea-872c-f4a2b208da64.png)

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:17:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**: 2.6.4

**What happened**: Already described above

**What you expected to happen**: Only one kubernetes configuration should be in place.

**How to reproduce it** (as minimally and precisely as possible):
Use the bellow values.yaml to install the chart:
```yaml
master:
  adminPassword: xxxxxxxxxxxxx

  installPlugins:
    - kubernetes
    - workflow-job
    - workflow-aggregator
    - credentials-binding
    - git
    - cloudbees-bitbucket-branch-source
    - parameterized-scheduler
    - active-directory
    - blueocean
    - configuration-as-code
    - job-dsl
    - terraform
    - aws-credentials
    - pipeline-aws

  JCasC:
    configScripts:
      my-settings: |
        jenkins:
          clouds:
          - kubernetes:
              containerCap: 10
              containerCapStr: "10"
              webSocket: true
              jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
              name: "kubernetes"
              namespace: "jenkins"
              podLabels:
              - key: "jenkins/jenkins-jenkins-slave"
                value: "true"
              serverUrl: "https://kubernetes.default"
              templates:
              - containers:
                - args: "^${computer.jnlpmac} ^${computer.name}"
                  envVars:
                  - containerEnvVar:
                      key: "JENKINS_URL"
                      value: "http://jenkins.jenkins.svc.cluster.local:8080"
                  image: "jenkins/jnlp-slave:3.27-1"
                  name: "jnlp"
                  resourceLimitCpu: "512m"
                  resourceLimitMemory: "512Mi"
                  resourceRequestCpu: "512m"
                  resourceRequestMemory: "512Mi"
                  workingDir: "/home/jenkins"
                label: "jenkins-jenkins-slave "
                name: "default"
                nodeUsageMode: NORMAL
                podRetention: "never"
                serviceAccount: "default"
                yamlMergeStrategy: "override"
          securityRealm:
            activeDirectory:
              domains:
                - name: "mydomain"
                  servers: "xxxxxxx"
                  bindName: 'xxxxxxxxxxx'
                  bindPassword: 'xxxxxxxxxxxx'
                  tlsConfiguration: TRUST_ALL_CERTIFICATES
              groupLookupStrategy: AUTO
              removeIrrelevantGroups: false
              cache:
                size: 250
                ttl: 10
              startTls: false
              internalUsersDatabase:
                jenkinsInternalUser: "jenkins"

persistence:
  enabled: true
  storageClass: "my-storage-class"
  size: "16Gi"
```
