### ISSUE TITLE
JCasC default config contains check doesn't catch named templates

### ISSUE THREAD

**Issue by miles-w-3** [jenkinsci/helm-charts#651]
### Describe the bug

When specifying jcasc custom configs, the built-in authorizationStrategy and securityRealm configs are not included in the default jcasc config if they are present in the custom scripts. This is does not work when the contents of the configScript piped sections are abstracted into named templates like so:

```
# custom-values.yaml
controller:
  JCasC:
    configScripts:
      test: |
        {{ include "tester" . }}
```

```
# _helpers.tpl
{{- define "tester" -}}
securityRealm: 
  local:
    allowsSignup: false
    enableCaptcha: false
    users:
    - id: "${chart-admin-username}"
        name: "Jenkins Admin"
        password: "${chart-admin-password}"
{{- end -}}
```

### Version of Helm and Kubernetes

```markdown
- Helm: 3.9.0
- Kubernetes: 1.24
```

### Chart version

jenkins-4.1.9

### What happened?

```bash
1. Add a new key within the configScripts value
2. Make its contents include a named template
3. Define the named template to include securityRealm
4. The outputted template will have two configurations for securityRealm
```

### What you expected to happen?

When the following values file is passed in, securityRealm is excluded properly. I expected the same functionality when I included.

```
controller:
  JCasC:
    configScripts:
      test: |
        jenkins:
          securityRealm: 
            local:
              allowsSignup: false
              enableCaptcha: false
              users:
              - id: "${chart-admin-username}"
                name: "Jenkins Admin"
                password: "${chart-admin-password}"
```

### How to reproduce it

```markdown
Create a configScript for securityRealm that calls a named template instead of dumping the files within the pipe
```

### Anything else we need to know?

I'll be experimenting with a way to find a solution using a helm function other than `contains`.  I think this use-case provides value because users can program in actual yaml instead of having everything piped, and then just pipe in using a template.  If i can get it working, I will submit with my pr for #650 since they both edit the jcasc template creation. Thanks for your time.
