### ISSUE TITLE
Ability to add environment variables from secrets in a Pod Template

### ISSUE THREAD

**Issue by mikekaram** [jenkinsci/helm-charts#656]
### Is your feature request related to a problem? Please describe

I have created some agents under the `additionalAgents` entry:
```
additionalAgents:
  dind:
    podName: dind
    ...
    TTYEnabled: true
  dind2:
    podName: dind2
    ...
    TTYEnabled: true
```
I would like to add to my `dind2` template some environment variables from secrets. Currently, the `envVars` is used for adding environment variables but this doesn't support the option to add environment variables from secrets.

### Describe the solution you'd like

The solution I would like to see is the following:

```
  dind2:
    podName: dind2
    ...
    TTYEnabled: true
    envVars:
      - name: myvariable1
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: var1
            optional: false
      - name: myvariable2
        valueFrom:
          secretKeyRef:
            name: my-secrets
            key: var2
            optional: false
```
So far, if I run `helm install` in the previous it is failing.
