### ISSUE TITLE
Change to initScripts does not trigger Jenkins to reinitialize

### ISSUE THREAD

**Issue by jimsnab** [jenkinsci/helm-charts#678]
### Describe the bug

When using initScripts, which turns into file changes in `init.groovy.d` usually, Jenkins is not instructed to reload its configuration, so the changes in `init.groovy.d` do not get processed until unrelated activity triggers the reload.

### Version of Helm and Kubernetes

```markdown
- Helm: version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}
- Kubernetes: 
Client Version: v1.24.3
Kustomize Version: v4.5.4
Server Version: v1.22.10-gke.600
```

### Chart version

jenkins-4.1.14

### What happened?

1. Have a setting created in initScripts, such as this:

```yaml
controller:
  initScripts:
    setup-known-hosts: |
      new File("/var/jenkins_home/.ssh").mkdir()
      File file = new File("/var/jenkins_home/.ssh/known_hosts")
      file.write '${known_hosts}'
```

Supply `${known_host}` with a sample from a `/home/user/.ssh/known_hosts` file.

2. Deploy Jenkins with Helm, and shell into the Jenkins pod and witness the `~/.ssh/known_hosts` file was created.
3. Update `${known_hosts}` in values.yaml with another host
4. Deploy Jenkins with Helm again, and shell in again, and witness the `~/.ssh/known_hosts` file was not updated.
5. Restart the Jenkins pod
5. Shell in again and witness the `~/.ssh/known_hosts` file was finally updated.

### What you expected to happen?

Jenkins reinitializes and picks up the change at initialization (possibly with a `values.yaml` option that must be enabled to grant the reload).

### How to reproduce it

See above
