### ISSUE TITLE
Setting persistence:volumes and persistence:mounts the Jenkins pod does not deploy.

### ISSUE THREAD

**Issue by andycockerill-cpi** [jenkinsci/helm-charts#679]
### Describe the bug

If I set the following under the "persistence" and "containerEnv" sections, the Jenkins pod does not deploy, but the services do:

```
controller:
  containerEnv:
      - name: GOOGLE_APPLICATION_CREDENTIALS 
        value: /var/jenkins_home/jenkins-test-project.json
persistence:
    enabled: true
    ## A manually managed Persistent Volume and Claim
    ## Requires persistence.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    existingClaim: jenkins-pvc
    ## jenkins data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass:
    annotations: {}
    accessMode: "ReadWriteOnce"
    size: "8Gi"
    volumes:
       - name: jenkins-serviceaccount
         secret:
           secretName: jenkins-serviceaccount
    mounts:
       - name: jenkins-serviceaccount
         mountPath: "/var/jenkins_home" 
         readOnly: true
```

### Version of Helm and Kubernetes

```markdown
- Helm: v3.9.2
- Kubernetes: v1.24.3
```

### Chart version

jenkins-4.1.14

### What happened?

```bash
1. helm install jenkins jenkins/jenkins -f values.yaml -n jenkins
NAME: jenkins
LAST DEPLOYED: Fri Aug  5 09:10:47 2022
NAMESPACE: jenkins
STATUS: deployed
REVISION: 1
NOTES:
1. Get your 'admin' user password by running:
  kubectl exec --namespace jenkins -it svc/jenkins -c jenkins -- /bin/cat /run/secrets/additional/chart-admin-password && echo
2. Get the Jenkins URL to visit by running these commands in the same shell:
  echo http://127.0.0.1:8080
  kubectl --namespace jenkins port-forward svc/jenkins 8080:8080

3. Login with the password from step 1 and the username: admin
4. Configure security realm and authorization strategy
5. Use Jenkins Configuration as Code by specifying configScripts in your values.yaml file, see documentation: http:///configuration-as-code and examples: https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos

For more information on running Jenkins on Kubernetes, visit:
https://cloud.google.com/solutions/jenkins-on-container-engine

For more information about Jenkins Configuration as Code, visit:
https://jenkins.io/projects/jcasc/


NOTE: Consider using a custom image with pre-installed plugins
2. kubectl get po -n jenkins
3. No resources found in jenkins namespace.
4. kubectl get svc -n jenkins
5. NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
jenkins         ClusterIP   10.106.223.201   <none>        8080/TCP    28m
jenkins-agent   ClusterIP   10.97.6.113      <none>        50000/TCP   28m
6. kubectl get secret -n jenkins
NAME                            TYPE                 DATA   AGE
jenkins                         Opaque               2      29m
jenkins-serviceaccount          Opaque               1      17h
jenkins-tls                     kubernetes.io/tls    2      13d
sh.helm.release.v1.jenkins.v1   helm.sh/release.v1   1      29m

...
```

### What you expected to happen?

I expected the pods to deploy, with a working Jenkins and the env var loaded from the volume mount.

### How to reproduce it

```markdown
controller:
  containerEnv:
    - name: GOOGLE_APPLICATION_CREDENTIALS 
      value: /var/jenkins_home/jenkins-test-project.json

persistence:
  enabled: true
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  existingClaim: jenkins-pvc
  ## jenkins data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass:
  annotations: {}
  accessMode: "ReadWriteOnce"
  size: "8Gi"
  volumes:
     - name: jenkins-serviceaccount
       secret:
         secretName: jenkins-serviceaccount
  mounts:
     - name: jenkins-serviceaccount
       mountPath: "/var/jenkins_home" 
       readOnly: true
```

### Anything else we need to know?

I'm deploying on bare metal using X86_64.
