### ISSUE TITLE
Env variable CASC_JENKINS_CONFIG is being overwritten

### ISSUE THREAD

**Issue by CzapBran** [jenkinsci/helm-charts#693]
### Describe the bug

I am deploying jenkins to a kubernetes cluster by providing an override values file.  In this values file, I am trying to set the CASC_JENKINS_CONFIG env variable to also include a path where I mounted my custom JCASC yaml file.

```
controller:
  ....
  containerEnv:
      - name: CASC_JENKINS_CONFIG
        value: "/var/jenkins_home/casc_configs,/var/jenkins_home/custom_casc_config"
  ....

mounts:
      - mountPath: /var/jenkins_home/custom_casc_config
        name: custom_jcasc_config
```

I am even building my own custom image of jenkins that sets the same as an env variable.  However, upon pod creation, I actually see that there are two CASC_JENKINS_CONFIG environment variables.  One of them is what I set, and the other is the defaul `/var/jenkins_home/casc_configs`.  When I shell into my pod and run `echo $CASC_JENKINS_CONFIG`, it returns  only `/var/jenkins_home/casc_configs`, which therefore means my custom yaml isn't being considered by the CasC plugin.  Is  this feature not supported?  Is there an issue updating the CASC_JENKINS_CONFIG env variable?

### Version of Helm and Kubernetes

```markdown
- Helm: 
- Kubernetes:
```

### Chart version

4.1.17

### What you expected to happen?

CASC_JENKINS_CONFIG uses the set value from the image / values-file

### How to reproduce it

Set an env variable for CASC_JENKINS_CONFIG in either the image, or the values file via the controller tag.  Deploy it to your cluster service.  Shell into the pod and echo the env variable.  It has been overwritten to the default value, rather than what you set.  If you describe the pod details however (using kubernetes terminology), you will see that there are two env variables with the same name located in the pod
