### ISSUE TITLE
Invite/confirm listed chart maintainers

### ISSUE THREAD

**Issue by scottrigby** [jenkinsci/helm-charts#7]
- [x] Invite existing maintainers to be collaborators on this repo
- [x] Contact the listed maintainers in `Chart.yaml` to see if they still wish to be involved
- [ ] Remove old maintainers who either have declined or not confirmed

**Comment by torstenwalter** [comment]
existing maintainers are already invited via [Hosting request](https://issues.jenkins-ci.org/browse/HOSTING-1015)

**Comment by scottrigby** [comment]
OK, have they all been emailed and asked if they still would like to maintain the chart in this new location? I updated the checklist above.

**Comment by torstenwalter** [comment]
I send a mail to all listed chart maintainers. Waiting for their feedback.
@scottrigby Thanks for triggering this!

```
maintainers:
- name: lachie83
  email: lachlan.evenson@microsoft.com
- name: viglesiasce
  email: viglesias@google.com
- name: maorfr
  email: maor.friedman@redhat.com
- name: torstenwalter
  email: mail@torstenwalter.de
- name: mogaal
  email: garridomota@gmail.com
- name: wmcdona89
  email: wmcdona89@gmail.com
```
