### ISSUE TITLE
plugin throttle-concurrents not enable when install

### ISSUE THREAD

**Issue by antonpatsev** [jenkinsci/helm-charts#701]
### Describe the bug

Value:

```
  additionalPlugins:
  - google-login:1.6
  - job-dsl:1.81
  - allure-jenkins-plugin:2.30.2
  - ws-cleanup:0.42
  - build-timeout:1.21
  - timestamper:1.18
  - google-storage-plugin:1.5.6
  - permissive-script-security:0.7
  - ansicolor:1.0.2
  - google-oauth-plugin:1.0.6
  - role-strategy:561.v9846c7351a_41
  - build-name-setter:2.2.0
  - uno-choice:2.6.4
  - throttle-concurrents:2.9
  imagePullPolicy: IfNotPresent
  installPlugins:
  - kubernetes:3600.v144b_cd192ca_a_
  - workflow-aggregator:581.v0c46fa_697ffd
  - git:4.11.5
  - configuration-as-code:1511.vb_f985b_894e40
  javaOpts: -Dpermissive-script-security.enabled=true
  numExecutors: 8
  tag: 2.346.3-2-lts
```

![image](https://user-images.githubusercontent.com/106875734/190051595-7a4f7caa-9451-40f8-b2f6-7b508c76e469.png)

How enable plugin when install chart?

### Version of Helm and Kubernetes

```markdown
- Helm: v3.5.0
- Kubernetes: v1.22.10-gke.600
```

### Chart version

4.1.17

### What happened?

```bash
1.
2.
3.
...
```
