### ISSUE TITLE
(k8s v1.25 bug?) compute-resources: must specify limits.cpu for: config-reload; limits.memory for: config-reload; requests.cpu for: config-reload; requests.memory for: config-reload

### ISSUE THREAD

**Issue by lknite** [jenkinsci/helm-charts#737]
### Describe the bug

```create Pod jenkins-0 in StatefulSet jenkins failed error: pods "jenkins-0" is forbidden: failed quota: compute-resources: must specify limits.cpu for: config-reload; limits.memory for: config-reload; requests.cpu for: config-reload; requests.memory for: config-reload```

### Version of Helm and Kubernetes

```markdown
- Helm:

$ helm version
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
```
- Kubernetes: 
```
$ kubectl version -o yaml
... <snip> ...
serverVersion:
  buildDate: "2022-09-12T20:11:31Z"
  compiler: gc
  gitCommit: 26e9405767263a2915723cb72b1ffd7f50687a8f
  gitTreeState: clean
  gitVersion: v1.25.0+k3s1
  goVersion: go1.19
  major: "1"
  minor: "25"
  platform: linux/amd64
```
```


### Chart version

jenkins:4.2.9

### What happened?

```bash
1. Install kubernetes v1.25
2. Deploy jenkins helm chart
```

### What you expected to happen?

Install the helm chart as before when I was running kubernetes 1.24

### How to reproduce it

```markdown
I applied a chart (jenkins: 4.1.12) which was working before but didn't work in my latest kubernetes installation.

I think the issue is probably related to having reinstalled my cluster using 1.25 .

Also tried with 4.2.9 to see if a fix might have been release, but no, same issue w/ 4.2.9 .
```

**Comment by lknite** [comment]
I added "limits to controller.sidecars.configAutoReload.resources.requests" which changes the error I'm getting.  I can see where the initial limits.cpu & limits.memory are getting their values, but I haven't yet figured out where the last limit of 'cpu=2' & 'memory=2Gi' are coming from.

```
create Pod jenkins-0 in StatefulSet jenkins failed error: pods "jenkins-0" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2200m,limits.memory=4296Mi, used: limits.cpu=0,limits.memory=0, limited: limits.cpu=2,limits.memory=2Gi
```

values.yaml:
```
  controller:
    resources:
      requests:
        cpu: "50m"
        memory: "256Mi"
      limits:
        cpu: "2000m"
        memory: "4096Mi"
    sidecars:
      configAutoReload:
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
```

**Comment by lknite** [comment]
was able to get it working by shrinking the memory limits to total under 2Gi, but I can't figure out where that 2Gi is coming from in the error message ... can someone help me out on where that's coming from?  I see 4 places where memory can be configured, but these don't seem to be the origin of that 2Gi.
```
  agent:
    resources:
      requests:
        cpu: "512m"
        memory: "512Mi"
        #cpu: "50m"
        #memory: "256Mi"
        #memory: "1024Mi"
#        ephemeral-storage: "1Gi"
      limits:
        cpu: "512m"
        memory: "512Mi"
#        ephemeral-storage: "2Gi"

  controller:
    resources:
      requests:
        cpu: "50m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "1024Mi"
    initContainerResources:
      requests:
        cpu: "50m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "2048Mi"
    sidecars:
      configAutoReload:
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
```
