### ISSUE TITLE
Load JCasC.configScripts from files in directory

### ISSUE THREAD

**Issue by kintarowins** [jenkinsci/helm-charts#743]
### Is your feature request related to a problem? Please describe

Currently I have to embed entire jcasc yaml files as yaml values. It would be cleaner and more organized to be able to load these from external files or a directory instead.

### Describe the solution you'd like

instead of configUrls and configScripts, have a configDir or configFiles to load them from the file system
```
  JCasC:
    defaultConfig: true
    configUrls: []
    configScripts: {}
    ### new options ###
    configDir: where/my/jcasc/files/at
    configFiles:
    - my/jcasc/files/config1.yaml
    - my/jcasc/files/config2yaml
```

### Describe alternatives you've considered

configUrls works but you need to host the files which would be a separate process and is difficult to version control
