### ISSUE TITLE
Multiple local paths in CASC_JENKINS_CONFIG

### ISSUE THREAD

**Issue by drewwaranissonos** [jenkinsci/helm-charts#747]
### Is your feature request related to a problem? Please describe

I want to extend `CASC_JENKINS_CONFIG` to be something like `/var/jenkins_home/casc_configs,/var/jenkins_home/custom-casc_configs,$ARBITARARY_NUMBER_OF_LOCAL_PATHS`.

When I try to set `CASC_JENKINS_CONFIG` directly I get an error that it is already set, but if I do
```
jenkins:
  controller
    sidecars:
      configAutoReload:
        folder: "/var/jenkins_home/casc_configs,/var/jenkins_home/custom-casc_configs"
```
as recommended I end up with
```
volumeMounts:
  - name: sc-config-volume
    mountPath: "/var/jenkins_home/casc_configs,/var/jenkins_home/custom-casc_configs"
```
which breaks the mount.

My goal here is to be to breakout my JCasC YAML into separate files and use the `override` `CASC_MERGE_STRATEGY` to DRY them out.

Thank you!

### Describe the solution you'd like

The chart is able to break up a list of comma-separated paths in `CASC_JENKINS_CONFIG` into individual paths and mount them into the Jenkins controller and sidecar separately.

### Describe alternatives you've considered

Turning off JCasC in the helm chart and enable JCasC manually.
