### ISSUE TITLE
ServiceMonitor metricRelabelings not correctly templated

### ISSUE THREAD

**Issue by dhhuynh2** [jenkinsci/helm-charts#771]
### Describe the bug

When setting metricRelabelings, helm will fail when installing the chart with the following error: 

```yaml
  Error: YAML parse error on jenkins/templates/jenkins-controller-servicemonitor.yaml: error converting YAML to JSON: yaml: line 19: did not find expected ',' or ']'
```

### Version of Helm and Kubernetes

```markdown
- Helm: v3.8.0
- Kubernetes: v1.20.15
```

### Chart version

4.2.15

### What happened?
1. Set `values.json` as such below (example):

```yaml
...
controller:
  ...
  prometheus:
    enabled: true
    ...
    metricRelabelings:
      - sourceLabels: [__name__]
        regex: "some_regex_(.*)"
        targetLabel: "someLabel"
      - sourceLabels: [__name__]
        regex: "another_regex(.*)"
        targetLabel: "anotherLabel"
```

2. Installed the chart.

3. Received:

`Error: YAML parse error on jenkins/templates/jenkins-controller-servicemonitor.yaml: error converting YAML to JSON: yaml: line 19: did not find expected ',' or ']'`

### What you expected to happen?

Chart should be correctly installed without YAML validation errors.

### How to reproduce it
Reproduced by locally templating `jenkins/templates/jenkins-controller-servicemonitor.yaml` file with my `values.json` values.

### Anything else we need to know?

After digging into the template, I see this is where it's being set:

https://github.com/jenkinsci/helm-charts/blob/2bbd9f0c6d49fd2d8f1a014ac53bd9f0b40ad363/charts/jenkins/templates/jenkins-controller-servicemonitor.yaml#L30

Since metricRelabelings is a list of maps, I believe this should be invoking `toYaml` as such:

```yaml
{{- toYaml .Values.controller.prometheus.metricRelabelings | trim | nindent 6 }}
```

I've noticed an open PR that should resolve this in https://github.com/jenkinsci/helm-charts/pull/638 if merged.
