### ISSUE TITLE
Helm Chart Failure - Various Issues

### ISSUE THREAD

**Issue by hilafish** [jenkinsci/helm-charts#778]
### Describe the bug

Hi all,

I'm trying to deploy helm chart version 4.2.15, on an EKS cluster.
The Jenkins pod is kept on READY 0/2, STATUS Init:0/1 due to the error-
`Unable to attach or mount volumes: unmounted volumes=[jenkins-home], unattached volumes=[jenkins-config plugins plugin-dir jenkins-home jenkins-cache tmp-volume sc-config-volume jenkins-secrets jenkins-deploy-key kube-api-access-kns87]: timed out waiting for the condition`

I read about it on the documentation, where it suggests to experiment with replacing fsGroup with supplementalGroups, so I did-
```
podSecurityContextOverride:
  runAsNonRoot: true
  runAsUser: 1000
  supplementalGroups: [1000]
```
And still got the same error.

First I tried to rely on dynamic provisioning and got this error. Then I deployed PVC on my own and defined configuration to use it-
```
persistence:
  enabled: true
  storageClass: "-"
  existingClaim: "jenkins-pvc"
```
And still got this error.

I searched the error on google and found that I need to install the CSI driver?
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md
I haven't found any reference to it on the chart or the documentation, so I don't know if it's because you think it's a common knowledge or because it's not really needed.
I'll try to install it but would appreciate any leads (or enforcing this CSI lead) to help me understand where the issue lies.

Thanks,
Hila

### Version of Helm and Kubernetes

```markdown
- Helm: v3.9.4
- Kubernetes: client version v1.22.0, server version v1.24.7-eks-fb459a0
```

### Chart version

4.2.15

### What happened?

```bash
1. deploy chart (hard to sum it in steps as there are configuration files)
2. get the volume error
```

### What you expected to happen?

pod is able to attach the volume and initialize properly

**Comment by hilafish** [comment]
After I installed the CSI Driver, I now get-
```
  Warning  FailedMount         11m (x21 over 38m)   kubelet                  MountVolume.WaitForAttach failed for volume "jenkins-pv" : volume attachment is being deleted
  Warning  FailedMount         2m7s (x10 over 17m)  kubelet                  (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[jenkins-home], unattached volumes=[plugins kube-api-access-tckxw sc-config-volume jenkins-deploy-key plugin-dir jenkins-cache jenkins-home jenkins-config jenkins-secrets tmp-volume]: timed out waiting for the condition
  Warning  FailedAttachVolume  74s (x26 over 38m)   attachdetach-controller  AttachVolume.Attach failed for volume "jenkins-pv" : volume attachment is being deleted
```

Any leads will be appreciated. PV and PVC looks good.

**Comment by hilafish** [comment]
After switching from csi to EBS, it works. Not clear why, and also not clear if this workaround is good enough or there's a specific reason to want CSI over pre(static)-provisioned EBS.

**Comment by hilafish** [comment]
Issue above solved. The documentation is invalid-
It says to set up this block-
```
          securityRealm: |-
            local:
              allowsSignup: false
              enableCaptcha: false
              users:
              - id: "${chart-admin-username}"
                name: "Jenkins Admin"
                password: "${chart-admin-password}"
          authorizationStrategy: |-
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false     
```
under  JCasC:

But actually it should be under -
```
  JCasC:        
    configScripts:       
        jenkins:
```  
This is the only way it works. Got it from the configration-as-code plugin documentation-
https://github.com/jenkinsci/configuration-as-code-plugin/blob/a6983ff60e0cf198ce02d7992bcba927197174db/demos/matrix-auth/README.md
