### ISSUE TITLE
Allow multiple JCasC paths to be set via environment variable

### ISSUE THREAD

**Issue by CzapBran** [jenkinsci/helm-charts#793]
### Is your feature request related to a problem? Please describe

As of now, when setting the values file for a helm install, the chart overrides any setting of CASC_JENKINS_CONFIG to one location (/var/jenkins_home/casc_configs).  This limits us in that we have to list our entire custom JCasC yaml nested in the values file.  For some, this creates a giant yaml file that becomes hard to track.

### Describe the solution you'd like

When installing via helm, it seems that helm is overriding the environment variable for the JCasC yaml location.  The JCasC plugin itself allows for multiple paths to be set in this variable, delimited by a comma.  We should be allowed to define our own CASC_JENKINS_CONFIG values to point to multiple JCasC yaml, breaking up the giant block within our values file.

**Comment by jslay-excella** [comment]
Shouldn't need to mess with `CASC_JENKINS_CONFIG`. You can already have separate override files for each JCasC you want.

Override `my-custom-config-1.yaml`
```YAML
controller:
  JCasC:
    configScripts:
      my-custom-config-1: |
        security:
          scriptApproval:
            approvedSignatures:
              - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
              - "new groovy.json.JsonSlurperClassic"
```

Override `my-custom-config-2.yaml`
```YAML
controller:
  JCasC:
    configScripts:
      my-custom-config-2: |
          jenkins:
            globalNodeProperties:
            - envVars:
                env:
                - key: "MY_GLOBAL_VAR"
                  value: "testing123"
```


Thats it.
