### ISSUE TITLE
configUrls options failing with remote jcasc yaml 

### ISSUE THREAD

**Issue by Swapnil-CSI** [jenkinsci/helm-charts#862]
### Describe the bug

I am trying to use configUrls option with remote url.
```
  JCasC:
    defaultConfig: true
    configUrls:
    - https://bitbucket.example.com/projects/ID/repos/example/raw/jenkins/jcasc/test.yaml
    configScripts: {}
```
But it is failing with below error. 
```
2023-04-28 10:42:37.175+0000 [id=32]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed ConfigurationAsCode.init
java.lang.IllegalArgumentException: Single entry map expected to configure a hudson.security.AuthorizationStrategy
        at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configureMapping(HeteroDescribableConfigurator.java:269)
        at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.preConfigure(HeteroDescribableConfigurator.java:251)
```
( Attached test.yaml file in text format )
[test.yaml.txt](https://github.com/jenkinsci/helm-charts/files/11352963/test.yaml.txt)

When I use same yaml in configScripts section it works.
```
  JCasC:
    defaultConfig: true
    #configUrls:
    #- https://bitbucket.example.com/projects/ID/repos/example/raw/jenkins/jcasc/test.yaml
    # - https://acme.org/jenkins.yaml
    # Remote URL:s for configuration files.
    configScripts:
      jenkins: |-
        jenkins:
          authorizationStrategy:
            roleBased:
              roles:
                global:
                  - name: "admin"
                    description: "Jenkins administrators"
                    permissions:
                      - "Overall/Administer"
                    assignments:
                      - "admin"
                  - name: "readonly"
                    description: "Read-only users"
                    permissions:
                      - "Overall/Read"
                      - "Job/Read"
                    assignments:
                      - "authenticated"
                items:
                  - name: "FolderA"
                    description: "Jobs in Folder A, but not the folder itself"
                    pattern: "A/.*"
                    permissions:
                      - "Job/Configure"
                      - "Job/Build"
                      - "Job/Delete"
                    assignments:
                      - "user1"
                      - "user2"
                  - name: "FolderB"
                    description: "Jobs in Folder B, but not the folder itself"
                    pattern: "B.*"
                    permissions:
                      - "Job/Configure"
                      - "Job/Build"
                    assignments:
                      - "user2"
```
