### ISSUE TITLE
ingress does not support api networking.k8s.io/v1

### ISSUE THREAD

**Issue by dilshad18** [jenkinsci/helm-charts#900]
### ingress object failed to apply due to unsupported keys
```
        serviceName: >-
           {{ template "jenkins.fullname" . }}
         # Don't use string here, use only integer value!
         servicePort: 8080

```
this throw an error 
ingress in version "v1" cannot be handled as a Ingress: strict decoding error: unknown field "spec.rules[0].http.paths[0].backend.serviceName", unknown field "spec.rules[0].http.paths[0].backend.serviceport"

### Version of Helm and Kubernetes

```markdown
- Helm: 
- Kubernetes:
```

### Chart version

4.5.0

### What happened?

```bash
ingress in version "v1" cannot be handled as a Ingress: strict decoding error: unknown field "spec.rules[0].http.paths[0].backend.serviceName", unknown field "spec.rules[0].http.paths[0].backend.serviceport"
...
```

### What you expected to happen?

```bash
      - backend:
          service:
            name: jenkins
            port:
              number: 8080
        path: /
        pathType: Prefix
```

### How to reproduce it
helm upgrade --install jenkins jenkins/jenkins -f values.yaml --create-namespace  -n jenkins-up

### Anything else we need to know?

This can be fixed by following code    

```yaml
- path: /
      pathType: Prefix
      backend:
        service:
          name: >-
            {{ template "jenkins.fullname" . }}
          port: 
            number: 8080
```
