### ISSUE TITLE
Jenkins-test doesn't support custom image repository

### ISSUE THREAD

**Issue by victtsl** [jenkinsci/helm-charts#916]
### Describe the bug

This configuration block is in my values.yaml 

```
  controller:
    componentName: "jenkins-controller"
    image: "artifacts.testinfra.net/docker-local/testinfra/jenkins-j11"
    tag: "jenkins-j11-npd-a31abaa"
    imagePullPolicy: "Always"

```

I have an issue using custom image and needing to test (controller.testEnabled=true) but it's not able to find the image because of [this line](https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/templates/tests/jenkins-test.yaml#L34). This value should be `image: "{{ .Values.controller.image }}:{{ .Values.controller.tag }}"` similar to StatefulSet manifest.

### Version of Helm and Kubernetes

```markdown
- Helm: v3.10.2
- Kubernetes: v1.24.15
```

### Chart version

jenkins-4.6.1

### What happened?

```bash
1. Create a helm values file with the following block

  controller:
    componentName: "jenkins-controller"
    image: "artifacts.testinfra.net/docker-local/testinfra/jenkins-j11"
    tag: "jenkins-j11-npd-a31abaa"
    imagePullPolicy: "Always"
```

2. Deploy helm chart with new values file
```
helm upgrade --install jenkins --namespace jenkins \
    -f values.yaml \
    artifacts.testinfra.net/docker-local/testinfra/jenkins-j11;
```

3. Deployment failed because jenkins-ui-test is unable to find image below: `artifacts.testinfra.net/docker-local/testinfra/jenkins-j11:2.414.1-jdk11`

### What you expected to happen?

Deployment successful without any errors

### How to reproduce it

```markdown
See step 1 in "What happened?" above
```
