### ISSUE TITLE
Jenkins chart v4.6.5+ - Deployment issue: Invalid URL https://{{ .Values.global.jenkinsHostName }}

### ISSUE THREAD

**Issue by Ceddaerrix** [jenkinsci/helm-charts#928]
### Describe the bug

When using the following configuration into _values.yaml_:
```
global:
  jenkinsHostname: "jenkins.my-org.com"

controller:
  ingress:
    enabled: true
    hostName: "{{ .Values.global.jenkinsHostname }}"
    resourceRootUrl: "{{ .Values.global.jenkinsHostname }}"
    tls:
      - hosts:
        - "{{ .Values.global.jenkinsHostname }}"
```

The following message appears into the Jenkins container logs:
`INFO	j.m.JenkinsLocationConfiguration#preventRootUrlBeingInvalid: Invalid URL received: https://{{ .Values.global.jenkinsHostName }}/, considered as null`

### Version of Helm and Kubernetes

```markdown
- Helm: v3.11.3"
- Kubernetes: v1.27.2
```

### Chart version

4.6.5+

### What happened?

```bash
Jenkins container logs:
INFO	j.m.JenkinsLocationConfiguration#preventRootUrlBeingInvalid: Invalid URL received: https://{{ .Values.global.jenkinsHostName }}/, considered as null
```

### What you expected to happen?

No such message

### How to reproduce it

```markdown
global:
  jenkinsHostname: "jenkins.my-org.com"

controller:
  ingress:
    enabled: true
    hostName: "{{ .Values.global.jenkinsHostname }}"
    resourceRootUrl: "{{ .Values.global.jenkinsHostname }}"
    tls:
      - hosts:
        - "{{ .Values.global.jenkinsHostname }}"
```
