### ISSUE TITLE
Jenkins pod priority cannot be set with priorityClassName parameter

### ISSUE THREAD

**Issue by SohamChakraborty** [jenkinsci/helm-charts#966]
Pod priority is not changing

Hi,

We are trying to give Jenkins pods a higher priority than 0.

For that we tried to set `priorityClassName` to an already existing priorityclass. After then we tried to upgrade the release with `helm upgrade`.  But the change doesn't get reflected. 

Any idea whether we are doing something wrong here? Has it worked for someone else? 

```
controller:
  componentName: "jenkins-controller"
  image: "jenkins/jenkins"
  tag: "lts-jdk11"
  imagePullPolicy: "Always"
  ...
  podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  priorityClassName: "pre-existing-priorityclass"
```

### Version of Helm and Kubernetes

```markdown
- Helm: v3.11.3
- Kubernetes: v1.23.5
```

### Chart version

jenkins-4.1.13

### What happened?

```bash
1. Change the parameter of `priorityClassName` in `values.yaml`.
2. Run `helm upgrade`.
3. The change is not being reflected.
...
```

### What you expected to happen?

The pod priority should change
