### ISSUE TITLE
`fsGroupChangePolicy: "OnRootMismatch"` is not set

### ISSUE THREAD

**Issue by dee-kryvenko** [jenkinsci/helm-charts#970]
### Describe the bug

This helm chart is setting `fsGroup`. When `fsGroup` is used, most of the times unless there are reasons not to - `fsGroupChangePolicy: "OnRootMismatch"` must be set. This is especially relevant for Jenkins with its CPS/survivability implementation. My Jenkins instance has 31 million xml files. To attach a volume - takes 15+ minutes, and that's super performant nvme ssd based volume. Probably could take an hour on a regular EBS or something like that.

### Version of Helm and Kubernetes

```markdown
- Helm: 
- Kubernetes:
```

### Chart version

irrelevant

### What happened?

```bash
1.
2.
3.
...
```

**Comment by timja** [comment]
Did you want to send a pull request?

**Comment by mohanisch-sixt** [comment]
As far as I can see `podSecurityContextOverride` should make it:

```yaml
  podSecurityContextOverride:
    runAsUser: 1000
    fsGroup: 1000
    fsGroupChangePolicy: "OnRootMismatch"
    runAsNonRoot: true
    supplementalGroups: [1000]
 ```
