### ISSUE TITLE
Make admin secret optional

### ISSUE THREAD

**Issue by egorksv** [jenkinsci/helm-charts#980]
### Is your feature request related to a problem? Please describe

Hi, 

I just noticed that the chart creates admin-password secret object in k8s. We are configuring SAML via JCasC and this is completely redundant and confusing.

### Describe the solution you'd like

Add option to disable k8s secret creation when configuration does not require it

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by egorksv** [comment]
Hi @kvanzuijlen 
Yes that's exactly what's needed - may I suggest moving it under `controller.admin`,  along with `controller.adminUser` as it's a bit inconsistent and confusing.

I.e instead of this:

```
  # The default configuration uses this secret to configure an admin user
  # If you don't need that user or use a different security realm then you can disable it
  adminSecret: true

  hostNetworking: false
  # When enabling LDAP or another non-Jenkins identity source, the built-in admin account will no longer exist.
  # If you disable the non-Jenkins identity store and instead use the Jenkins internal one,
  # you should revert controller.adminUser to your preferred admin user:
  adminUser: "admin"
  # adminPassword: <defaults to random>
  admin:
    existingSecret: ""
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password

```

Do something like this:
```
controller:
  admin:
    # The default configuration uses this secret to configure an admin user
    # If you don't need that user or use a different security realm then you can disable it
    enabled: true/false
    # When enabling LDAP or another non-Jenkins identity source, the built-in admin account will no longer exist.
    # If you disable the non-Jenkins identity store and instead use the Jenkins internal one,
    # you should revert controller.admin.username to your preferred admin user:
    username:
    existingSecret: ""
    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password
```
