### ISSUE TITLE
JenkinsURL is undefined

### ISSUE THREAD

**Issue by romankydybets** [jenkinsci/helm-charts#981]
### Describe the bug

I am setting up next params
```
  serviceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-name: "jenkins-network-lb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    external-dns.alpha.kubernetes.io/hostname: "jenkins-cicd.test.com"
    external-dns.alpha.kubernetes.io/ttl: "60"
  serviceType: LoadBalancer
  servicePort: 80
  jenkinsUrl: "jenkins-cicd.test.com"
  jenkinsUrlProtocol: "https"
  ```
  but each time when i changing something and login into the jenkins -> Manage Jenkins -> i see the JenkinsUrl is undefined,
  Then i go to `System` and see the values. so i click just `save` and everything went fine, to the next changes.
  
  

### Version of Helm and Kubernetes

```markdown
- Helm: 
- Kubernetes:
```

### Chart version

4.11.2

### What happened?

```bash
1.
2.
3.
...
```

### What you expected to happen?

I expected not to have this, as i would like fully automated updated

**Comment by YakovHerz** [comment]
I'm pretty sure you need to set it either for the controller or the agent:
`controller.jenkinsUrl` or `agent.jenkinsUrl`

**Comment by romankydybets** [comment]
@YakovHerz  i did like this initially
```
values:
  controller:
      JCasC:
        jenkinsUrl: jenkins-cicd.test.com
        jenkinsUrlProtocol: https
```
